using System;using System.Collections.Generic;using System.Linq;using System.IO;
using Unity.Entities;using Game.Tools;using Game.Rendering;using Game.Common;using TrafficLightIntoKorea;
class Program {
 static int checks;static void Check(bool ok,string label){checks++;if(!ok)throw new Exception(label);}
 static Entity Make(EntityManager em,bool allocated=true){var e=em.Create();em.AddComponent<KoreanSignalClone>(e);em.AddComponentData(e,new CullingInfo{m_PassedCulling=1});em.AddComponentData(e,allocated?new List<MeshBatch>{new MeshBatch()}:new List<MeshBatch>());return e;}
 static void Main(){
  const int lights=64,frames=600;var em=new EntityManager();var entities=Enumerable.Range(0,lights).Select(_=>Make(em)).ToArray();var attempts=new int[lights];var next=new float[lights];var oldAttempts=new int[lights];var oldNext=new float[lights];UnityEngine.Time.realtimeSinceStartup=1;
  for(int i=0;i<lights;i++){SignalRenderReadiness.Repair(em,entities[i],ref attempts[i],ref next[i]);BaselineSignalRenderReadiness.Repair(em,entities[i],ref oldAttempts[i],ref oldNext[i]);}em.Writes.Clear();
  for(int frame=0;frame<frames;frame++){UnityEngine.Time.realtimeSinceStartup=1+frame/60f;for(int i=0;i<lights;i++){SignalRenderReadiness.Repair(em,entities[i],ref attempts[i],ref next[i]);BaselineSignalRenderReadiness.Repair(em,entities[i],ref oldAttempts[i],ref oldNext[i]);}}
  em.Writes.TryGetValue(typeof(KoreanRenderState),out int writes);em.Writes.TryGetValue(typeof(BaselineKoreanRenderState),out int oldWrites);Check(writes==0&&oldWrites==lights*frames,"Stable rendering must stop repeated state writes");Console.WriteLine($"64 displays x 600 frames: baseline state writes={oldWrites}; new state writes={writes}");
  var e=entities[0];int a=0;float n=0;em.GetBuffer<MeshBatch>(e,true).Clear();UnityEngine.Time.realtimeSinceStartup=20;SignalRenderReadiness.Repair(em,e,ref a,ref n);Check(SignalRenderReadiness.MainReady(em,e),"Batch-loss grace retained");Check(em.HasComponent<Updated>(e)&&a==1,"Missing visible batch schedules repair");em.RemoveComponent<Updated>(e);em.RemoveComponent<BatchesUpdated>(e);UnityEngine.Time.realtimeSinceStartup=20.5f;SignalRenderReadiness.Repair(em,e,ref a,ref n);Check(!em.HasComponent<Updated>(e),"Repair throttled between retries");UnityEngine.Time.realtimeSinceStartup=21.2f;Check(!SignalRenderReadiness.MainReady(em,e),"Persistent missing batch restores native fallback");em.AddComponent<Hidden>(e);SignalRenderReadiness.Repair(em,e,ref a,ref n);Check(SignalRenderReadiness.MainReady(em,e),"Offscreen known-ready display retained");em.RemoveComponent<Hidden>(e);em.GetBuffer<MeshBatch>(e,true).Add(new MeshBatch());SignalRenderReadiness.Repair(em,e,ref a,ref n);Check(SignalRenderReadiness.MainReady(em,e)&&a==0&&n==0,"Recovered batch resets retry state");
  em.AddComponent<Overridden>(e);SignalRenderReadiness.Protect(em,e);Check(!em.HasComponent<Overridden>(e)&&em.HasComponent<Updated>(e),"Override protection still works");var temp=Make(em);em.AddComponent<Temp>(temp);SignalRenderReadiness.Repair(em,temp,ref a,ref n);Check(!em.HasComponent<KoreanRenderState>(temp),"Save-time Temp excluded");var never=Make(em,false);Check(!SignalRenderReadiness.MainReady(em,never),"Never-ready remains native");
  int reconciles=0;float due=0;for(int i=0;i<600;i++){float now=i/60f;if(SignalMaintenanceRules.Due(now,due)){reconciles++;due=now+SignalMaintenanceRules.SignInterval;}}Check(reconciles<=40&&reconciles>=38,"Idle sign reconciliation bounded to 4 Hz");Console.WriteLine($"One idle parent, 10 seconds at 60 fps: at most {reconciles} periodic reconciliations vs 2400 old singleton visits.");
  var root=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"../../../../"));string Read(string f)=>File.ReadAllText(Path.Combine(root,"src",f));var far=Read("FarSignalSystem.cs");var sync=far.Substring(far.IndexOf("internal void Sync()"));Check(!sync.Contains("IndividualSignalData")&&!Read("CombinedFarSignal.cs").Contains("IndividualSignalData"),"No save-key lookup in far per-frame sync");Check(far.Contains("old.Manual=plan.Manual")&&far.Contains("Manual=plan.Manual"),"Manual state refreshed on both reuse and creation");var sign=Read("TrafficSignSystem.cs");Check(sign.Contains("e.NextReconcile")&&sign.Contains("_pending.Dequeue();_queued.Remove(e);Reconcile(e);"),"Manual edits bypass periodic throttle");var directional=Read("DirectionalLightSystem.cs");Check(directional.Contains("GetBuffer<Emissive>(e,true)")&&directional.Contains("GetBuffer<LightState>(e,true)")&&directional.Contains("if(entryChanged){emissiveWrites[m]=entry;"),"Light buffers read first and written only on changes");Check(!directional.Contains("CompleteDependencyBeforeRW"),"No unconditional global writer barrier in light update");
  Console.WriteLine($"PASS: {checks} performance/regression checks. ECS harness, not in-game FPS.");
 }
}
