using System.Collections.Generic;using Game;using Game.Common;using Game.Objects;using Game.Prefabs;using Game.Rendering;using Game.Tools;using Unity.Entities;using Unity.Collections;using Unity.Mathematics;
namespace TrafficLightIntoKorea {
public struct ApproachVisual:IComponentData {}
public partial class ApproachSignalSystem:GameSystemBase {
 private readonly JunctionWatch _watch=new JunctionWatch();
 private readonly SignalStartupScan _startup=new SignalStartupScan();
 protected override void OnDestroy(){_startup.Dispose();base.OnDestroy();}
 private sealed class Entry{internal Entity Clone,Owner,Prefab,BasePrefab,Pedestrian;internal quaternion Alignment;internal bool OwnsPedestrianHidden,HideNear;internal ushort PedestrianMask;internal KoreanSignalTransition Transition;internal int BatchAttempts;internal float NextBatch;internal bool OwnsHidden,FallbackReported;internal readonly HashSet<Entity> HiddenChildren=new HashSet<Entity>();internal readonly List<Entity> Children=new List<Entity>();}
 private readonly Dictionary<Entity,Entry> _entries=new Dictionary<Entity,Entry>();
 private readonly Dictionary<Entity,Entity> _straightOnly=new Dictionary<Entity,Entity>();
 private readonly Dictionary<Entity,Entity> _turnOnly=new Dictionary<Entity,Entity>();
 private readonly Dictionary<Entity,Entity> _eligible=new Dictionary<Entity,Entity>();
 private readonly List<Entity> _pending=new List<Entity>(),_remove=new List<Entity>();private readonly HashSet<Entity> _queued=new HashSet<Entity>();private int _head;private bool _ready,_active,_saving;
 private Entity _lastVehicleTarget,_lastCrosswalkTarget;
 private void RefreshSelections(){var vehicle=Mod.Settings.StraightLeftVehicleAsset??"";var crossing=Mod.Settings.StraightLeftCrosswalkAsset??"";ApproachCatalog.Resolve(EntityManager,vehicle,false,out var v);ApproachCatalog.Resolve(EntityManager,crossing,true,out var c);if(vehicle==_vehicle&&crossing==_crosswalk&&v==_lastVehicleTarget&&c==_lastCrosswalkTarget)return;_vehicle=vehicle;_crosswalk=crossing;_lastVehicleTarget=v;_lastCrosswalkTarget=c;_startup.Request();World.GetExistingSystemManaged<FarSignalSystem>()?.RefreshAll();}
 private string _vehicle="",_crosswalk="";private EntityQuery _signals,_changed,_changedSignals;
 protected override void OnCreate(){base.OnCreate();_signals=GetEntityQuery(ComponentType.ReadOnly<TrafficLight>(),ComponentType.ReadOnly<Transform>(),ComponentType.ReadOnly<PrefabRef>(),ComponentType.Exclude<FarSignal>(),ComponentType.Exclude<ApproachVisual>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>());_changed=GetEntityQuery(ComponentType.ReadOnly<Game.Net.SubLane>(),ComponentType.ReadOnly<Game.Objects.SubObject>(),ComponentType.ReadOnly<Updated>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>());_changedSignals=GetEntityQuery(new EntityQueryDesc{All=new[]{ComponentType.ReadOnly<TrafficLight>(),ComponentType.ReadOnly<Owner>()},Any=new[]{ComponentType.ReadOnly<Created>(),ComponentType.ReadOnly<Updated>()},None=new[]{ComponentType.ReadOnly<FarSignal>(),ComponentType.ReadOnly<ApproachVisual>(),ComponentType.ReadOnly<Deleted>(),ComponentType.ReadOnly<Temp>()}});}
 protected override void OnGamePreload(Colossal.Serialization.Entities.Purpose purpose,GameMode mode){Clear();_ready=false;base.OnGamePreload(purpose,mode);}
 protected override void OnGameLoadingComplete(Colossal.Serialization.Entities.Purpose purpose,GameMode mode){base.OnGameLoadingComplete(purpose,mode);_ready=mode==GameMode.Game;_active=false;_startup.Reset();_vehicle=Mod.Settings?.StraightLeftVehicleAsset??"";_crosswalk=Mod.Settings?.StraightLeftCrosswalkAsset??"";}
 private bool Live(Entity e)=>EntityManager.Exists(e)&&!EntityManager.HasComponent<Deleted>(e)&&!EntityManager.HasComponent<KoreanRetired>(e);
 private Entity OwnerOf(Entity e){if(!EntityManager.Exists(e))return Entity.Null;for(int i=0;i<4&&EntityManager.HasComponent<Owner>(e);i++){e=EntityManager.GetComponentData<Owner>(e).m_Owner;if(EntityManager.HasBuffer<Game.Net.SubLane>(e)&&EntityManager.HasBuffer<Game.Objects.SubObject>(e))return e;}return Entity.Null;}
 private void Queue(Entity e){_watch.Track(e);if(e!=Entity.Null&&_queued.Add(e))_pending.Add(e);}
 private void Mark(Entity e){if(!EntityManager.HasComponent<BatchesUpdated>(e))EntityManager.AddComponent<BatchesUpdated>(e);}
 private void Delete(Entity e){World.GetExistingSystemManaged<TrafficSignSystem>()?.Forget(e);if(Live(e))World.GetOrCreateSystemManaged<KoreanVisualLifecycleSystem>().Retire(e);}
 private void Release(Entity source,Entry entry){ReleasePedestrianMerge(entry);World.GetExistingSystemManaged<DirectionalLightSystem>()?.Unlink(entry.Clone);Delete(entry.Clone);foreach(var child in entry.HiddenChildren)if(Live(child)&&EntityManager.HasComponent<Hidden>(child)){EntityManager.RemoveComponent<Hidden>(child);Mark(child);}entry.HiddenChildren.Clear();var left=World.GetExistingSystemManaged<LeftSignalSystem>();if(entry.OwnsHidden&&Live(source)&&EntityManager.HasComponent<Hidden>(source)&&!(left?.IsHiddenTarget(source)??false)){EntityManager.RemoveComponent<Hidden>(source);Mark(source);}}
 internal void Clear(){_watch.Clear();_startup.Reset();foreach(var p in _entries){Release(p.Key,p.Value);World.GetExistingSystemManaged<LeftSignalSystem>()?.RefreshOwner(p.Value.Owner);}_entries.Clear();_eligible.Clear();_turnOnly.Clear();_straightOnly.Clear();_pending.Clear();_queued.Clear();_head=0;_active=false;}

 internal void CollectOwners(HashSet<Entity> owners){foreach(var e in _entries.Values)owners.Add(e.Owner);}
 internal void RemoveOwner(Entity owner){ClearTurnOnly(owner);_watch.Untrack(owner);_remove.Clear();foreach(var p in _entries)if(p.Value.Owner==owner)_remove.Add(p.Key);foreach(var e in _remove){Release(e,_entries[e]);_entries.Remove(e);_eligible.Remove(e);}_remove.Clear();foreach(var p in _eligible)if(p.Value==owner)_remove.Add(p.Key);foreach(var e in _remove)_eligible.Remove(e);}
 private Entity ConfiguredTarget(Entity source){var ps=World.GetExistingSystemManaged<PrefabSystem>();if(!ps.TryGetPrefab<StaticObjectPrefab>(source,out var original)||original==null)return Entity.Null;var name=Mod.Settings.Selection(original.name);if(string.IsNullOrEmpty(name))return Entity.Null;if(name=="CSKRTL4w2l"||name=="CS KR Traffic Light 4w2l")name=Catalog.Alias??name;if(!Catalog.Entries.TryGetValue(name,out var target)||target==source)return Entity.Null;return World.GetExistingSystemManaged<OverrideSystem>().RegularProxy(target);}
 internal void RefreshOwner(Entity owner){Queue(owner);}
 internal void RefreshAll(){_startup.Request();}
 internal bool NearSuppressed(Entity source)=>_entries.TryGetValue(source,out var entry)&&entry.HideNear&&(World.GetExistingSystemManaged<FarSignalSystem>()?.DisplayReady(source)??false);
 internal Entity DisplayFor(Entity source)=>_entries.TryGetValue(source,out var entry)&&Live(entry.Clone)?entry.Clone:Entity.Null;
 internal bool IsVisualSource(Entity e)=>_active&&_entries.ContainsKey(e);
 internal Entity VehicleTarget(Entity source){if(IsTurnOnly(source)||IsStraightOnly(source))return ThreeLampTarget(source,false,IsTurnOnly(source));if(_entries.TryGetValue(source,out var chosen))return chosen.BasePrefab;if(!_active||!Mod.Settings.UseStraightLeftAssets)return Entity.Null;if(_eligible.ContainsKey(source))return ApproachCatalog.Resolve(EntityManager,_vehicle,false,out var target)?target:Entity.Null;if(!Live(source)||!EntityManager.HasComponent<PrefabRef>(source))return Entity.Null;var prefab=EntityManager.GetComponentData<PrefabRef>(source).m_Prefab;return DirectChoice(prefab)?RegularTarget(OwnerOf(source),prefab,true):Entity.Null;}
 internal Entity CombinedTarget(Entity source){if(IsTurnOnly(source)||IsStraightOnly(source))return ThreeLampTarget(source,true,IsTurnOnly(source));if(!_active||!Live(source)||!EntityManager.HasComponent<PrefabRef>(source))return Entity.Null;if(_eligible.ContainsKey(source))return ApproachCatalog.Resolve(EntityManager,_crosswalk,true,out var target)?target:Entity.Null;if(_entries.TryGetValue(source,out var chosen)&&IsCombined(chosen.BasePrefab))return chosen.BasePrefab;var prefab=EntityManager.GetComponentData<PrefabRef>(source).m_Prefab;var configured=ConfiguredTarget(prefab);if(IsCombined(configured))return configured;if(DirectChoice(prefab)&&EntityManager.HasComponent<TrafficLightData>(prefab)&&((int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&12)!=0)return RegularTarget(OwnerOf(source),prefab,false);return Entity.Null;}
 private bool IsCombined(Entity prefab)=>prefab!=Entity.Null&&EntityManager.Exists(prefab)&&EntityManager.HasComponent<TrafficLightData>(prefab)&&((int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&3)!=0&&((int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&12)!=0;
 internal bool ExpectsCustom(Entity source){if(IsTurnOnly(source)||IsStraightOnly(source)||_eligible.ContainsKey(source)||_entries.ContainsKey(source))return true;if(!EntityManager.HasComponent<PrefabRef>(source))return false;var ps=World.GetExistingSystemManaged<PrefabSystem>();return ps.TryGetPrefab<StaticObjectPrefab>(EntityManager.GetComponentData<PrefabRef>(source).m_Prefab,out var p)&&!string.IsNullOrEmpty(Mod.Settings.Selection(p.name));}
 private bool DirectChoice(Entity prefab)=>Catalog.Entries.TryGetValue(_vehicle,out var v)&&v==prefab||Catalog.Entries.TryGetValue(_crosswalk,out var c)&&c==prefab;
 // Match the regular visual by traffic-light type and local road theme only.
 private Entity RegularTarget(Entity owner,Entity source,bool vehicleOnly){
  if(!EntityManager.HasComponent<TrafficLightData>(source))return Entity.Null;
  int type=(int)EntityManager.GetComponentData<TrafficLightData>(source).m_Type&15;if(vehicleOnly)type&=3;
  var prefabs=World.GetExistingSystemManaged<PrefabSystem>();string theme="";
  if(EntityManager.HasBuffer<Game.Objects.SubObject>(owner))foreach(var item in EntityManager.GetBuffer<Game.Objects.SubObject>(owner,true)){var e=item.m_SubObject;if(!EntityManager.HasComponent<PrefabRef>(e))continue;if(prefabs.TryGetPrefab<StaticObjectPrefab>(EntityManager.GetComponentData<PrefabRef>(e).m_Prefab,out var p)&&(p.name.StartsWith("NA_")||p.name.StartsWith("EU_"))){theme=p.name.Substring(0,3);break;}}
  Entity candidate=Entity.Null;string candidateName="";int best=-1;
  foreach(var name in SourceNames.All){if(!Catalog.Entries.TryGetValue(name,out var e)||!EntityManager.HasComponent<TrafficLightData>(e)||((int)EntityManager.GetComponentData<TrafficLightData>(e).m_Type&15)!=type)continue;int score=name.StartsWith(theme)&&theme.Length>0?2:0;
if(score>best){candidate=e;candidateName=name;best=score;}}
  if(candidate==Entity.Null)return Entity.Null;
  string choice=Mod.Settings.Selection(candidateName);if(string.IsNullOrEmpty(choice)||!Catalog.Entries.TryGetValue(choice,out var selected)||!EntityManager.HasComponent<TrafficLightData>(selected)||(((int)EntityManager.GetComponentData<TrafficLightData>(selected).m_Type&12)==0)!=((type&12)==0))return Entity.Null;candidate=selected;
  return World.GetExistingSystemManaged<OverrideSystem>().RegularProxy(candidate);
 }
 internal void DescribeApproaches(Entity owner,System.Text.StringBuilder report){report.AppendLine("TOPOLOGY ConnectedRoads="+LaneTopology.LiveRoads(EntityManager,owner).Count+" PreferFour="+ThreeLampRules.PreferFour(LaneTopology.LiveRoads(EntityManager,owner).Count));foreach(var name in new[]{_vehicle,_crosswalk}){if(Catalog.Entries.TryGetValue(name,out var selected))report.AppendLine("SELECTED "+name+" Entity="+selected+" Proxy="+World.GetExistingSystemManaged<OverrideSystem>().ApproachProxyStatus(selected));else report.AppendLine("SELECTED "+name+" catalog missing");}if(!EntityManager.HasBuffer<Game.Objects.SubObject>(owner))return;foreach(var item in EntityManager.GetBuffer<Game.Objects.SubObject>(owner,true)){var e=item.m_SubObject;if(!Live(e)||!EntityManager.HasComponent<TrafficLight>(e)||!EntityManager.HasComponent<Transform>(e)||!EntityManager.HasComponent<PrefabRef>(e))continue;var p=EntityManager.GetComponentData<PrefabRef>(e).m_Prefab;report.AppendLine("APPROACH Source="+e+" StraightOnlyCached="+IsStraightOnly(e)+" TurnOnlyCached="+IsTurnOnly(e)+" StraightLeftNow="+IsStraightLeft(owner,e)+" DirectSelectedAsset="+DirectChoice(p)+" EligibleCached="+_eligible.ContainsKey(e)+" Overlay="+(_entries.TryGetValue(e,out var entry)?entry.Prefab.ToString():"none"));}}

 protected override void OnUpdate(){using(RuntimeDiagnostics.Measure("ApproachSignalSystem.OnUpdate")){if(_saving)return;bool on=_ready&&Mod.Settings!=null&&Mod.Settings.Enabled;if(!on){if(_active){Clear();World.GetExistingSystemManaged<FarSignalSystem>()?.RefreshAll();}return;}
 RefreshSelections();
 if(!_active){_active=true;_startup.Request();World.GetExistingSystemManaged<FarSignalSystem>()?.RefreshAll();}
 _watch.Tick(EntityManager,Queue);
 _startup.Tick(_signals,OwnerOf,node=>{if(KoreanJunctionSystem.Selected(EntityManager,node))Queue(node);},UnityEngine.Time.realtimeSinceStartup);
 
 
 for(int i=0;i<2&&_head<_pending.Count&&SignalWorkBudget.TakeOwner();i++){var owner=_pending[_head++];_queued.Remove(owner);Rebuild(owner);World.GetExistingSystemManaged<LeftSignalSystem>()?.RefreshOwner(owner);World.GetExistingSystemManaged<FarSignalSystem>()?.RefreshOwner(owner);}if(_head==_pending.Count){_pending.Clear();_head=0;}}}
 private bool TryMovements(Entity owner,Entity source,out int movements,out bool turnOnly){
 movements=0;turnOnly=false;if(!EntityManager.HasComponent<Transform>(source)||!SignalApproach.Try(EntityManager,owner,EntityManager.GetComponentData<Transform>(source),out int road,out _))return false;
 var roads=LaneTopology.LiveRoads(EntityManager,owner);int valid=0;
 foreach(var sub in EntityManager.GetBuffer<Game.Net.SubLane>(owner,true)){var e=sub.m_SubLane;if(!UsableLane(e))continue;var lane=EntityManager.GetComponentData<Game.Net.Lane>(e);if(!LaneTopology.ConnectsLiveRoads(roads,lane)||lane.m_StartNode.GetOwnerIndex()!=road||lane.m_EndNode.GetOwnerIndex()==road)continue;
 var flags=EntityManager.GetComponentData<Game.Net.CarLane>(e).m_Flags;if((flags&(Game.Net.CarLaneFlags.Forbidden|Game.Net.CarLaneFlags.UTurnLeft|Game.Net.CarLaneFlags.UTurnRight))!=0)continue;var curve=EntityManager.GetComponentData<Game.Net.Curve>(e).m_Bezier;var start=math.normalizesafe((curve.b-curve.a).xz);var end=math.normalizesafe((curve.d-curve.c).xz);if(math.lengthsq(start)<.9f||math.lengthsq(end)<.9f)continue;valid++;movements|=MovementGeometry.Classify(flags,math.dot(start,end),start.x*end.y-start.y*end.x);}
 turnOnly=ThreeLampRules.TurnOnly(roads.Count,valid,movements);return valid>0;
 }
 private bool IsStraightLeft(Entity owner,Entity source)=>TryMovements(owner,source,out var movements,out _)&&ApproachRules.StraightLeft(movements);
 internal bool IsStraightOnly(Entity source)=>_straightOnly.ContainsKey(source);
 internal bool IsTurnOnly(Entity source)=>_turnOnly.ContainsKey(source);
 private void ClearTurnOnly(Entity owner){var straightRemove=new List<Entity>();foreach(var p in _straightOnly)if(p.Value==owner)straightRemove.Add(p.Key);foreach(var e in straightRemove)_straightOnly.Remove(e);var remove=new List<Entity>();foreach(var p in _turnOnly)if(p.Value==owner)remove.Add(p.Key);foreach(var e in remove)_turnOnly.Remove(e);}
 private Entity ThreeLampTarget(Entity source,bool crossing,bool leftArrow=true){
 if(!EntityManager.HasComponent<PrefabRef>(source))return Entity.Null;var ps=World.GetExistingSystemManaged<PrefabSystem>();var prefab=EntityManager.GetComponentData<PrefabRef>(source).m_Prefab;string original=ps.TryGetPrefab<StaticObjectPrefab>(prefab,out var p)?p.name:"";string preferred=Mod.Settings.Selection(original);if(string.IsNullOrEmpty(preferred))preferred=crossing?_crosswalk:_vehicle;
 string best=null;int score=-1;foreach(var name in Catalog.Vehicles){if(!Catalog.Entries.TryGetValue(name,out var e)||!EntityManager.Exists(e)||!EntityManager.HasComponent<TrafficLightData>(e)||!EntityManager.HasComponent<ObjectData>(e))continue;int type=(int)EntityManager.GetComponentData<TrafficLightData>(e).m_Type;if(!ThreeLampRules.Compatible(type,crossing))continue;int rank=ThreeLampRules.Score(name,preferred,original,leftArrow);if(rank>score||(rank==score&&rank>=0&&string.CompareOrdinal(name,best)<0)){score=rank;best=name;}}
 return best==null?Entity.Null:World.GetExistingSystemManaged<OverrideSystem>().RegularProxy(Catalog.Entries[best]);
 }
 private bool UsableLane(Entity lane)=>Live(lane)&&!EntityManager.HasComponent<Temp>(lane)&&!EntityManager.HasComponent<Game.Net.MasterLane>(lane)&&EntityManager.HasComponent<Game.Net.Lane>(lane)&&EntityManager.HasComponent<Game.Net.CarLane>(lane)&&EntityManager.HasComponent<Game.Net.Curve>(lane);
 private void Rebuild(Entity owner){ClearTurnOnly(owner);if(!KoreanJunctionSystem.Selected(EntityManager,owner)){RemoveOwner(owner);return;}if(!Live(owner)||!EntityManager.HasBuffer<Game.Objects.SubObject>(owner)){_remove.Clear();foreach(var p in _entries)if(p.Value.Owner==owner)_remove.Add(p.Key);foreach(var e in _remove){Release(e,_entries[e]);_entries.Remove(e);}_remove.Clear();foreach(var p in _eligible)if(p.Value==owner)_remove.Add(p.Key);foreach(var e in _remove)_eligible.Remove(e);return;}
 _remove.Clear();foreach(var pair in _eligible)if(pair.Value==owner)_remove.Add(pair.Key);foreach(var e in _remove)_eligible.Remove(e);
 bool preferFour=ThreeLampRules.PreferFour(LaneTopology.LiveRoads(EntityManager,owner).Count);var manualWanted=new Dictionary<Entity,Entity>();var wanted=new Dictionary<Entity,Entity>();using(var a=EntityManager.GetBuffer<Game.Objects.SubObject>(owner,true).ToNativeArray(Allocator.Temp))foreach(var item in a){var e=item.m_SubObject;if(!Live(e)||EntityManager.HasComponent<Temp>(e)||!EntityManager.HasComponent<TrafficLight>(e)||!EntityManager.HasComponent<Transform>(e)||!EntityManager.HasComponent<PrefabRef>(e))continue;var prefab=EntityManager.GetComponentData<PrefabRef>(e).m_Prefab;if(!EntityManager.HasComponent<TrafficLightData>(prefab) )continue;
 var manual=World.GetExistingSystemManaged<IndividualSignalData>().Target(owner,e,Entity.Null,false);if(manual!=Entity.Null)manualWanted[e]=manual;
 // Four-way topology takes precedence over movement-based three-lamp selection.
 if(preferFour&&((int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&3)!=0){_eligible[e]=owner;bool combined=((int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&12)!=0;if(ApproachCatalog.Resolve(EntityManager,combined?_crosswalk:_vehicle,combined,out var four))wanted[e]=four;continue;}
 if(TryMovements(owner,e,out var movements,out var turnOnly)&&(turnOnly||ThreeLampRules.StraightOnly(movements))&&((int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&3)!=0){if(turnOnly)_turnOnly[e]=owner;else _straightOnly[e]=owner;_eligible.Remove(e);var three=ThreeLampTarget(e,((int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&12)!=0,turnOnly);if(three!=Entity.Null)wanted[e]=three;continue;}else _turnOnly.Remove(e);
 if(!Mod.Settings.UseStraightLeftAssets||((int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&3)==0||!IsStraightLeft(owner,e)){var regular=ConfiguredTarget(prefab);if(regular!=Entity.Null)wanted[e]=regular;continue;}
 _eligible[e]=owner;int crossing=(int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&12;if(!ApproachCatalog.Resolve(EntityManager,crossing==0?_vehicle:_crosswalk,crossing!=0,out var target)){target=ConfiguredTarget(prefab);if(target==Entity.Null)continue;}
 if(target!=prefab)wanted[e]=target;}
 foreach(var pick in manualWanted)if(!wanted.ContainsKey(pick.Key))wanted[pick.Key]=pick.Value;
 _remove.Clear();foreach(var pair in _entries)if(pair.Value.Owner==owner&&!wanted.ContainsKey(pair.Key))_remove.Add(pair.Key);foreach(var e in _remove){Release(e,_entries[e]);_entries.Remove(e);}
 foreach(var pair in wanted){var source=pair.Key;bool hideNear=World.GetExistingSystemManaged<IndividualSignalData>().Get(owner,source)?.nearHidden??false;var aligned=SignalAlignment.Align(EntityManager,owner,source,EntityManager.GetComponentData<Transform>(source));var target=World.GetExistingSystemManaged<IndividualSignalData>().Target(owner,source,pair.Value,false);if(_entries.TryGetValue(source,out var entry)&&Live(entry.Clone)&&entry.Prefab==target){entry.BasePrefab=pair.Value;entry.HideNear=hideNear;entry.Alignment=aligned.m_Rotation;CollectChildren(source,entry,0);continue;}if(entry!=null)Release(source,entry);
 var clone=EntityManager.CreateEntity(EntityManager.GetComponentData<ObjectData>(target).m_Archetype);EntityManager.AddComponent<ApproachVisual>(clone);EntityManager.AddComponent<KoreanSignalClone>(clone);EntityManager.AddComponentData(clone,new Owner{m_Owner=owner});EntityManager.AddComponentData(clone,new IndividualSignalLink{Source=source,Owner=owner,Far=false});EntityManager.SetComponentData(clone,new PrefabRef{m_Prefab=target});EntityManager.SetComponentData(clone,aligned);EntityManager.SetComponentData(clone,EntityManager.GetComponentData<TrafficLight>(source));if(EntityManager.HasComponent<PseudoRandomSeed>(clone)&&EntityManager.HasComponent<PseudoRandomSeed>(source))EntityManager.SetComponentData(clone,EntityManager.GetComponentData<PseudoRandomSeed>(source));World.GetExistingSystemManaged<DirectionalLightSystem>()?.Link(clone,source);_entries[source]=new Entry{Clone=clone,Owner=owner,Prefab=target,BasePrefab=pair.Value,HideNear=hideNear,Alignment=aligned.m_Rotation};CollectChildren(source,_entries[source],0);}RebuildPedestrianMerges(owner);}
 private void CollectChildren(Entity source,Entry entry,int depth){if(depth>=8||entry.Children.Count>=64||!EntityManager.HasBuffer<Game.Objects.SubObject>(source))return;foreach(var item in EntityManager.GetBuffer<Game.Objects.SubObject>(source,true)){var child=item.m_SubObject;if(!Live(child)||child==source||child==entry.Clone||entry.Children.Contains(child))continue;entry.Children.Add(child);CollectChildren(child,entry,depth+1);if(entry.Children.Count>=64)break;}}
 internal void SyncVisibility(){using(RuntimeDiagnostics.Measure("ApproachSignalSystem.SyncVisibility")){if(_saving)return;_remove.Clear();var left=World.GetExistingSystemManaged<LeftSignalSystem>();foreach(var pair in _entries){var source=pair.Key;var entry=pair.Value;var clone=entry.Clone;if(!Live(source)||!Live(entry.Owner)||!Live(clone)||!EntityManager.HasComponent<TrafficLight>(source)||!EntityManager.HasComponent<Transform>(source)||!KoreanJunctionSystem.Selected(EntityManager,entry.Owner)){if(!Live(clone)&&Live(source)&&KoreanJunctionSystem.Selected(EntityManager,entry.Owner))Queue(entry.Owner);Release(source,entry);_remove.Add(source);continue;}
 bool manualHidden=entry.HideNear&&(World.GetExistingSystemManaged<FarSignalSystem>()?.DisplayReady(source)??false);
 bool leftHidden=manualHidden||(left?.IsHiddenTarget(source)??false)||MergedPedestrianHidden(source)||(World.GetExistingSystemManaged<FarSignalSystem>()?.MergedPedestrianHidden(source)??false);
 // Batch readiness controls only source visibility, never overlay synchronization.
 SignalRenderReadiness.Repair(EntityManager,clone,ref entry.BatchAttempts,ref entry.NextBatch);
 if(!manualHidden&&!SignalRenderReadiness.MainReady(EntityManager,clone)){
  if(!entry.FallbackReported){entry.FallbackReported=true;RuntimeDiagnostics.Event("Native fallback: custom mesh not ready owner="+entry.Owner+" source="+source+" clone="+clone+" target="+entry.Prefab);}
  if(entry.OwnsHidden&&!leftHidden&&EntityManager.HasComponent<Hidden>(source)){EntityManager.RemoveComponent<Hidden>(source);Mark(source);entry.OwnsHidden=false;}
  foreach(var child in entry.HiddenChildren)if(Live(child)&&EntityManager.HasComponent<Hidden>(child)){EntityManager.RemoveComponent<Hidden>(child);Mark(child);}entry.HiddenChildren.Clear();
 }else{
 entry.FallbackReported=false;
 if(!EntityManager.HasComponent<Hidden>(source)){EntityManager.AddComponent<Hidden>(source);entry.OwnsHidden=true;Mark(source);}
 foreach(var child in entry.Children)if(Live(child)&&!EntityManager.HasComponent<Hidden>(child)){EntityManager.AddComponent<Hidden>(child);entry.HiddenChildren.Add(child);Mark(child);}
 }
 bool hidden=EntityManager.HasComponent<Hidden>(clone);if(hidden!=leftHidden){if(leftHidden)EntityManager.AddComponent<Hidden>(clone);else EntityManager.RemoveComponent<Hidden>(clone);Mark(clone);}
 var t=EntityManager.GetComponentData<Transform>(source);t.m_Rotation=entry.Alignment;if(!t.Equals(EntityManager.GetComponentData<Transform>(clone))){EntityManager.SetComponentData(clone,t);if(!EntityManager.HasComponent<Updated>(clone))EntityManager.AddComponent<Updated>(clone);}var native=MergePedestrianState(entry,EntityManager.GetComponentData<TrafficLight>(source));if(native.m_GroupMask1==0)native=FarVehicleRules.VehicleState(native);var state=SignalVisualTransition.Apply(ref entry.Transition,native,World);if(!state.Equals(EntityManager.GetComponentData<TrafficLight>(clone)))EntityManager.SetComponentData(clone,state);
 World.GetExistingSystemManaged<TrafficSignSystem>()?.SyncParent(source);World.GetExistingSystemManaged<TrafficSignSystem>()?.SyncParent(clone);
 }foreach(var e in _remove){_entries.Remove(e);_eligible.Remove(e);}foreach(var entry in _entries.Values)SyncPedestrianMerge(entry);}}
 internal void BeforeSave(){_saving=true;SuspendPedestrianMerges();foreach(var p in _entries)if(Live(p.Value.Clone)&&!EntityManager.HasComponent<Temp>(p.Value.Clone))EntityManager.AddComponent<Temp>(p.Value.Clone);}
 internal void AfterSave(){foreach(var p in _entries)if(Live(p.Value.Clone)&&EntityManager.HasComponent<Temp>(p.Value.Clone))EntityManager.RemoveComponent<Temp>(p.Value.Clone);_saving=false;}
}
public partial class ApproachVisibilitySystem:GameSystemBase{protected override void OnUpdate(){World.GetExistingSystemManaged<ApproachSignalSystem>()?.SyncVisibility();}}
}

