using Game.Net;using Game.Prefabs;using Game.Common;using Game.Tools;using Unity.Entities;
namespace TrafficLightIntoKorea {
// Absence of a road/turn is not a prohibition. Require actual forbidden lane evidence.
internal static class BanRestrictions {
 internal static string Read(EntityManager em,Entity node,Entity edge,out bool known){known=false;if(!em.Exists(node)||!em.Exists(edge)||!em.HasBuffer<Game.Net.SubLane>(node))return null;int allowed=0,forbidden=0,explicitBans=0;if(em.HasComponent<Composition>(edge)&&em.HasComponent<Edge>(edge)){var c=em.GetComponentData<Composition>(edge);bool start=em.GetComponentData<Edge>(edge).m_Start==node;var p=start?c.m_StartNode:c.m_EndNode;if(em.HasComponent<NetCompositionData>(p)){var flags=em.GetComponentData<NetCompositionData>(p).m_Flags;var side=((flags.m_General&CompositionFlags.General.Invert)!=0)!=start?flags.m_Left:flags.m_Right;if((side&CompositionFlags.Side.ForbidStraight)!=0)explicitBans|=1;if((side&CompositionFlags.Side.ForbidLeftTurn)!=0)explicitBans|=2;if((side&CompositionFlags.Side.ForbidRightTurn)!=0)explicitBans|=4;known=true;}}foreach(var item in em.GetBuffer<Game.Net.SubLane>(node,true)){var e=item.m_SubLane;if(!em.Exists(e)||em.HasComponent<Deleted>(e)||em.HasComponent<Temp>(e)||em.HasComponent<MasterLane>(e)||!em.HasComponent<Game.Net.CarLane>(e)||!em.HasComponent<Lane>(e))continue;var lane=em.GetComponentData<Lane>(e);if(lane.m_StartNode.GetOwnerIndex()!=edge.Index)continue;var flags=em.GetComponentData<Game.Net.CarLane>(e).m_Flags;int bit=(flags&(CarLaneFlags.UTurnLeft|CarLaneFlags.UTurnRight))!=0?8:(flags&(CarLaneFlags.TurnLeft|CarLaneFlags.GentleTurnLeft))!=0?2:(flags&(CarLaneFlags.TurnRight|CarLaneFlags.GentleTurnRight))!=0?4:1;known=true;if((flags&CarLaneFlags.Forbidden)!=0)forbidden|=bit;else allowed|=bit;}
 return Choose(explicitBans|(forbidden&~allowed));
 }
 internal static string Choose(int bans){return (bans&1)!=0?SignRules.Prefix+"BanStraight":(bans&2)!=0?SignRules.Prefix+"BanLeft":(bans&4)!=0?SignRules.Prefix+"BanRight":(bans&8)!=0?SignRules.Prefix+"BanUTurn":null;}
}}
