using System.Collections.Generic;using Game.Common;using Game.Objects;using Game.Prefabs;using Game.Rendering;using Game.Tools;using Unity.Entities;using Unity.Mathematics;
namespace TrafficLightIntoKorea {
internal static class CombinedSignalRules {
 internal static TrafficLight Merge(TrafficLight vehicle,TrafficLight pedestrian){vehicle.m_GroupMask1=pedestrian.m_GroupMask1;vehicle.m_State=(TrafficLightState)(((int)vehicle.m_State&15)|((int)pedestrian.m_State&240));return vehicle;}
 internal static bool Anchor(float forward,float sideways,float rise,float distanceSquared)=>FarDestinationRules.Pedestrian(forward,sideways,rise,distanceSquared);
}
public partial class FarSignalSystem {
 private readonly Dictionary<Entity,Entry> _pedestrianEntries=new Dictionary<Entity,Entry>();
 internal bool ClaimsPedestrian(Entity pedestrian)=>_pedestrianEntries.ContainsKey(pedestrian);
 internal bool MergedPedestrianHidden(Entity pedestrian)=>_pedestrianEntries.TryGetValue(pedestrian,out var entry)&&Live(entry.Clone)&&!EntityManager.HasComponent<Hidden>(entry.Clone)&&SignalRenderReadiness.MainReady(EntityManager,entry.Clone);
 private Entity CombinedPrefab(Entity source,Entity prefab){var approach=World.GetExistingSystemManaged<ApproachSignalSystem>();if(approach?.IsTurnOnly(source)??false)return approach.CombinedTarget(source);var target=World.GetExistingSystemManaged<ApproachSignalSystem>()?.CombinedTarget(source)??Entity.Null;if(target!=Entity.Null)return target;if(approach?.ExpectsCustom(source)??false)return Entity.Null;
 if(EntityManager.HasComponent<TrafficLightData>(prefab)&&((int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&12)!=0)return prefab;
 var prefabs=World.GetExistingSystemManaged<PrefabSystem>();if(!prefabs.TryGetPrefab<StaticObjectPrefab>(prefab,out var original))return Entity.Null;string theme=original.name.StartsWith("EU_")?"EU_":original.name.StartsWith("NA_")?"NA_":"";if(theme.Length==0)return Entity.Null;
 int vehicle=(int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&3;foreach(var name in SourceNames.All)if(name.StartsWith(theme)&&Catalog.Entries.TryGetValue(name,out var e)&&EntityManager.HasComponent<TrafficLightData>(e)&&EntityManager.HasComponent<ObjectData>(e)){int type=(int)EntityManager.GetComponentData<TrafficLightData>(e).m_Type;if((type&3)==vehicle&&(type&12)!=0&&EntityManager.GetComponentData<ObjectData>(e).m_Archetype.Valid)return e;}return Entity.Null;
 }
 private bool TryPedestrianAnchor(Entity owner,Entity source,float3 origin,float2 direction,float3 desired,RoadSurface roads,HashSet<Entity> claimed,out Entity pedestrian,out float3 point,Entity destination=default,System.Text.StringBuilder report=null){pedestrian=Entity.Null;point=origin;float best=float.MaxValue;int candidateMask=0;bool ambiguous=false;var sourceState=EntityManager.GetComponentData<TrafficLight>(source);
 foreach(var item in EntityManager.GetBuffer<Game.Objects.SubObject>(owner,true)){var e=item.m_SubObject;if(e==source||claimed.Contains(e)||(World.GetExistingSystemManaged<ApproachSignalSystem>()?.ClaimsPedestrian(e)??false)||!Live(e)||EntityManager.HasComponent<Temp>(e)||!EntityManager.HasComponent<TrafficLight>(e)||!EntityManager.HasComponent<Transform>(e)||!EntityManager.HasComponent<PrefabRef>(e))continue;var p=EntityManager.GetComponentData<PrefabRef>(e).m_Prefab;if(!EntityManager.HasComponent<TrafficLightData>(p)||((int)EntityManager.GetComponentData<TrafficLightData>(p).m_Type&3)!=0)continue;var state=EntityManager.GetComponentData<TrafficLight>(e);if(state.m_GroupMask1==0||state.m_GroupMask0!=0||(sourceState.m_GroupMask1!=0&&(sourceState.m_GroupMask1&state.m_GroupMask1)==0))continue;var pos=EntityManager.GetComponentData<Transform>(e).m_Position;if(!(destination!=Entity.Null?OnDestinationSide(owner,destination,direction,pos):OnDrivingSide(owner,origin,direction,pos)))continue;var delta=pos-origin;float forward=math.dot(delta.xz,direction);float side=delta.x*direction.y-delta.z*direction.x;float distance=math.distancesq(pos.xz,desired.xz);if(!CombinedSignalRules.Anchor(forward,side,delta.y,distance))continue;if(!PedestrianMergeGeometry.SameCrosswalkEnd(EntityManager,owner,desired,pos,state.m_GroupMask1,36f)){report?.AppendLine("MERGE reject crossing end pedestrian="+e+" distance="+math.sqrt(distance));continue;}if(!ClearRoad(pos,roads,true)){report?.AppendLine("MERGE reject road clearance pedestrian="+e);continue;}
 if(candidateMask!=0&&candidateMask!=state.m_GroupMask1)ambiguous=true;candidateMask=state.m_GroupMask1;float score=distance+side*side;if(score<best){best=score;pedestrian=e;point=pos;}}
 if(ambiguous){pedestrian=Entity.Null;point=origin;report?.AppendLine("MERGE ambiguous pedestrian groups");}report?.AppendLine("MERGE selected="+pedestrian+" anchor="+point);return pedestrian!=Entity.Null;
 }
 private TrafficLight DisplayState(Entity source,Entity pedestrian,bool manual){if(manual){var display=World.GetExistingSystemManaged<ApproachSignalSystem>().DisplayFor(source);if(Live(display)&&EntityManager.HasComponent<TrafficLight>(display))return EntityManager.GetComponentData<TrafficLight>(display);return EntityManager.GetComponentData<TrafficLight>(source);}var state=EntityManager.GetComponentData<TrafficLight>(source);return pedestrian==Entity.Null?FarVehicleRules.VehicleState(state):CombinedSignalRules.Merge(state,EntityManager.GetComponentData<TrafficLight>(pedestrian));}
 private void HidePedestrian(Entry entry){if(EntityManager.HasComponent<Hidden>(entry.Clone)||!SignalRenderReadiness.MainReady(EntityManager,entry.Clone)){var old=entry.Pedestrian;if(entry.OwnsPedestrianHidden&&Live(old)&&PersistentSignalVisibility.HiddenOrOwned(EntityManager,old)){PersistentSignalVisibility.Show(EntityManager,old);if(!EntityManager.HasComponent<BatchesUpdated>(old))EntityManager.AddComponent<BatchesUpdated>(old);}entry.OwnsPedestrianHidden=false;return;}var e=entry.Pedestrian;if(e==Entity.Null||!Live(e))return;if(!EntityManager.HasComponent<Hidden>(e)){PersistentSignalVisibility.Hide(EntityManager,e);entry.OwnsPedestrianHidden=true;RuntimeDiagnostics.Count("far.pedestrianHideWrite");if(!EntityManager.HasComponent<BatchesUpdated>(e))EntityManager.AddComponent<BatchesUpdated>(e);}}
 private void ReleaseFar(Entry entry){if(_pedestrianEntries.TryGetValue(entry.Pedestrian,out var mapped)&&mapped==entry)_pedestrianEntries.Remove(entry.Pedestrian);World.GetExistingSystemManaged<DirectionalLightSystem>()?.Unlink(entry.Clone);Delete(entry.Clone);var e=entry.Pedestrian;if(entry.OwnsPedestrianHidden&&e!=Entity.Null&&Live(e)&&PersistentSignalVisibility.HiddenOrOwned(EntityManager,e)){PersistentSignalVisibility.Show(EntityManager,e);if(!EntityManager.HasComponent<BatchesUpdated>(e))EntityManager.AddComponent<BatchesUpdated>(e);}entry.OwnsPedestrianHidden=false;}
}
}

