using System;using System.Collections.Generic;using Game;using Game.Common;using Game.Objects;using Game.Prefabs;using Game.Rendering;using Game.Tools;using Game.UI.Widgets;using Unity.Collections;using Unity.Entities;using Unity.Mathematics;
namespace TrafficLightIntoKorea {
public partial class DirectionalLightSystem:GameSystemBase {
 private sealed class SourceInfo{internal Entity Owner;internal readonly List<Entity> Left=new List<Entity>(),Straight=new List<Entity>();internal bool Known;internal TrafficLight LeftState,StraightState;internal int Frame=-1;internal KoreanSignalTransition StraightTransition,LeftTransition;internal int StraightDisplay=1,LeftDisplay=1;}
 private sealed class Binding{internal Entity Source;internal bool LeftThree,NormalThree,Four;internal SourceInfo Info;internal int2 Cell;}
 private readonly Dictionary<Entity,int[]> _normalThreeMaps=new Dictionary<Entity,int[]>();
 private readonly Dictionary<Entity,int[]> _leftThreeMaps=new Dictionary<Entity,int[]>();
 private readonly Dictionary<Entity,Entity> _sources=new Dictionary<Entity,Entity>();private readonly Dictionary<Entity,SourceInfo> _info=new Dictionary<Entity,SourceInfo>();private readonly Dictionary<Entity,Binding> _bindings=new Dictionary<Entity,Binding>();private readonly Dictionary<int2,HashSet<Entity>> _cells=new Dictionary<int2,HashSet<Entity>>();private readonly Dictionary<Entity,int[]> _maps=new Dictionary<Entity,int[]>();private readonly List<Entity> _pending=new List<Entity>();private readonly HashSet<Entity> _queued=new HashSet<Entity>();private int _head;private string _signature="";private bool _lastKorean;private float _lastAmber;private bool _ready;private readonly SignalStartupScan _startup=new SignalStartupScan();private readonly JunctionWatch _watch=new JunctionWatch();private EntityQuery _signals,_changed;internal static string Status="0 / 0";
 protected override void OnCreate(){base.OnCreate();_signals=GetEntityQuery(ComponentType.ReadOnly<TrafficLight>(),ComponentType.ReadOnly<Transform>(),ComponentType.ReadOnly<PrefabRef>(),ComponentType.Exclude<FarSignal>(),ComponentType.Exclude<ApproachVisual>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>());_changed=GetEntityQuery(ComponentType.ReadOnly<TrafficLight>(),ComponentType.ReadOnly<Transform>(),ComponentType.ReadOnly<Updated>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>());}
 protected override void OnGamePreload(Colossal.Serialization.Entities.Purpose p,GameMode m){Clear();_ready=false;base.OnGamePreload(p,m);}
 protected override void OnGameLoadingComplete(Colossal.Serialization.Entities.Purpose p,GameMode m){base.OnGameLoadingComplete(p,m);_ready=m==GameMode.Game;_startup.Reset();}
 protected override void OnDestroy(){_startup.Dispose();base.OnDestroy();}
 internal void Clear(){_startup.Reset();_watch.Clear();_sources.Clear();_info.Clear();_bindings.Clear();_cells.Clear();_maps.Clear();_leftThreeMaps.Clear();_normalThreeMaps.Clear();_pending.Clear();_queued.Clear();_head=0;Status="0 / 0";}
 private bool Live(Entity e)=>EntityManager.Exists(e)&&!EntityManager.HasComponent<Deleted>(e)&&!EntityManager.HasComponent<Temp>(e);
 internal Entity OriginalSource(Entity e)=>_sources.TryGetValue(e,out var source)?source:e;
 internal void Link(Entity clone,Entity source){_sources[clone]=source;Queue(clone);World.GetExistingSystemManaged<TrafficSignSystem>()?.Queue(clone);}
 internal void Unlink(Entity e){_sources.Remove(e);if(_bindings.TryGetValue(e,out var b)){if(_cells.TryGetValue(b.Cell,out var set))set.Remove(e);_bindings.Remove(e);}}
 private void Queue(Entity e){if(e!=Entity.Null&&_queued.Add(e))_pending.Add(e);}
 private Entity OwnerOf(Entity e){if(_sources.TryGetValue(e,out var source))e=source;for(int i=0;i<4&&Live(e)&&EntityManager.HasComponent<Owner>(e);i++){e=EntityManager.GetComponentData<Owner>(e).m_Owner;if(EntityManager.HasBuffer<Game.Net.SubLane>(e)&&EntityManager.HasBuffer<Game.Objects.SubObject>(e))return e;}return Entity.Null;}
 internal void RemoveOwner(Entity owner){_watch.Untrack(owner);var remove=new List<Entity>();foreach(var p in _bindings)if(p.Value.Info.Owner==owner)remove.Add(p.Key);foreach(var e in remove)Unlink(e);}
 internal void RefreshOwner(Entity owner){if(!KoreanJunctionSystem.Selected(EntityManager,owner)||!Live(owner)||!EntityManager.HasBuffer<Game.Objects.SubObject>(owner))return;_watch.Track(owner);foreach(var pair in _sources)if(OwnerOf(pair.Key)==owner)Queue(pair.Key);}
 internal void Index(){if(!_ready)return;_watch.Tick(EntityManager,RefreshOwner);var timer=System.Diagnostics.Stopwatch.StartNew();for(int i=0;i<64&&_head<_pending.Count&&timer.ElapsedMilliseconds<2;i++){var e=_pending[_head++];_queued.Remove(e);Bind(e);}if(_head==_pending.Count){_pending.Clear();_head=0;}}
 private void Bind(Entity e){if(!_sources.ContainsKey(e)||!Live(e)||!EntityManager.HasComponent<Transform>(e)||!EntityManager.HasComponent<TrafficLight>(e))return;var source=_sources.TryGetValue(e,out var original)?original:e;var owner=OwnerOf(source);if(owner==Entity.Null||!Live(source)||!EntityManager.HasComponent<Transform>(source)||!EntityManager.HasComponent<TrafficLight>(source))return;_watch.Track(owner);
 if(!_info.TryGetValue(source,out var info)){info=new SourceInfo();_info[source]=info;}info.Owner=owner;info.Known=false;info.Left.Clear();info.Straight.Clear();info.Frame=-1;var roads=LaneTopology.LiveRoads(EntityManager,owner);
 if(SignalApproach.Try(EntityManager,owner,EntityManager.GetComponentData<Transform>(source),out int road,out var direction)){info.Known=true;foreach(var item in EntityManager.GetBuffer<Game.Net.SubLane>(owner,true)){var lane=item.m_SubLane;if(!Usable(lane,roads)||EntityManager.GetComponentData<Game.Net.Lane>(lane).m_StartNode.GetOwnerIndex()!=road)continue;var curve=EntityManager.GetComponentData<Game.Net.Curve>(lane).m_Bezier;var start=math.normalizesafe((curve.b-curve.a).xz);var end=math.normalizesafe((curve.d-curve.c).xz);int movement=MovementGeometry.Classify(EntityManager.GetComponentData<Game.Net.CarLane>(lane).m_Flags,math.dot(start,end),start.x*end.y-start.y*end.x);if(movement==2)info.Left.Add(lane);else if(movement==1)info.Straight.Add(lane);}}
 if(_bindings.TryGetValue(e,out var previous)&&_cells.TryGetValue(previous.Cell,out var old))old.Remove(e);var cell=(int2)math.floor(EntityManager.GetComponentData<Transform>(e).m_Position.xz/256f);if(!_cells.TryGetValue(cell,out var set)){set=new HashSet<Entity>();_cells[cell]=set;}set.Add(e);_bindings[e]=new Binding{Source=source,LeftThree=LeftThreeLampRules.Asset(AssetName(e)),NormalThree=AssetName(e).StartsWith("CSKR3w",StringComparison.OrdinalIgnoreCase)&&!LeftThreeLampRules.Asset(AssetName(e)),Four=AssetName(e).StartsWith("CSKR4w",StringComparison.OrdinalIgnoreCase),Info=info,Cell=cell};}
 private bool Usable(Entity e,HashSet<int> roads)=>Live(e)&&!EntityManager.HasComponent<Game.Net.MasterLane>(e)&&EntityManager.HasComponent<Game.Net.Lane>(e)&&EntityManager.HasComponent<Game.Net.CarLane>(e)&&EntityManager.HasComponent<Game.Net.Curve>(e)&&EntityManager.HasComponent<Game.Net.LaneSignal>(e)&&LaneTopology.ConnectsLiveRoads(roads,EntityManager.GetComponentData<Game.Net.Lane>(e));
 private void State(List<Entity> lanes,Game.Net.TrafficLights node,ref TrafficLight state,bool allowYield){
 ushort mask=0;bool go=false,yield=false,safeStop=false;
 foreach(var lane in lanes)if(Live(lane)&&EntityManager.HasComponent<Game.Net.LaneSignal>(lane)&&EntityManager.HasComponent<Game.Net.CarLane>(lane)&&(EntityManager.GetComponentData<Game.Net.CarLane>(lane).m_Flags&Game.Net.CarLaneFlags.Forbidden)==0){
 var signal=EntityManager.GetComponentData<Game.Net.LaneSignal>(lane);mask|=signal.m_GroupMask;
 if(signal.m_GroupMask==0)continue;
 go|=signal.m_Signal==Game.Net.LaneSignalType.Go;yield|=signal.m_Signal==Game.Net.LaneSignalType.Yield;safeStop|=signal.m_Signal==Game.Net.LaneSignalType.SafeStop;
 }
 state.m_GroupMask0=mask;state.m_GroupMask1=0;Game.Simulation.TrafficLightSystem.UpdateTrafficLightState(node,ref state);
 state.m_State=(TrafficLightState)MovementSignalState.Resolve(go,yield,safeStop,allowYield,node.m_State==Game.Net.TrafficLightState.Beginning,(int)state.m_State);
 }
 private readonly HashSet<string> _targetNames=new HashSet<string>(StringComparer.Ordinal);
 private string AssetName(Entity e){if(!EntityManager.HasComponent<PrefabRef>(e))return "";var prefab=EntityManager.GetComponentData<PrefabRef>(e).m_Prefab;var original=World.GetExistingSystemManaged<OverrideSystem>()?.VisualSource(prefab)??Entity.Null;if(original!=Entity.Null)prefab=original;return World.GetExistingSystemManaged<PrefabSystem>().TryGetPrefab<StaticObjectPrefab>(prefab,out var p)?p.name:"";}
 private int[] ThreeMap(Entity mesh,bool left){var cache=left?_leftThreeMaps:_normalThreeMaps;if(cache.TryGetValue(mesh,out var result))return result;result=new[]{-1,-1,-1};var ps=World.GetExistingSystemManaged<PrefabSystem>();if(ps.TryGetPrefab<RenderPrefab>(mesh,out var p)&&p.TryGet<EmissiveProperties>(out var props)&&props.m_MultiLights!=null){int[] ids={FixedSignalData.RedId,FixedSignalData.YellowId,left?FixedSignalData.ArrowId:FixedSignalData.StraightId};bool valid=true;for(int role=0;role<3;role++){int matches=0;for(int i=0;i<props.m_MultiLights.Count;i++)if(props.m_MultiLights[i].layerId==ids[role]){result[role]=i;matches++;}if(matches!=1){valid=false;continue;}var required=role==0?EmissiveProperties.Purpose.TrafficLight_Red:role==1?EmissiveProperties.Purpose.TrafficLight_Yellow:EmissiveProperties.Purpose.TrafficLight_Green;if(props.m_MultiLights[result[role]].purpose!=required)valid=false;}if(!valid)result=new[]{-1,-1,-1};}cache[mesh]=result;return result;}
 private int[] Map(Entity mesh,bool managedFour){if(_maps.TryGetValue(mesh,out var result))return result;result=new int[8];for(int i=0;i<8;i++)result[i]=-1;var ps=World.GetExistingSystemManaged<PrefabSystem>();if(ps.TryGetPrefab<RenderPrefab>(mesh,out var p)&&(_targetNames.Contains(p.name)||managedFour)&&p.TryGet<EmissiveProperties>(out var props)&&props.m_MultiLights!=null){var ids=Ids();var used=new HashSet<int>();bool valid=true;int count=Mod.Settings.SecondHead?8:4;for(int role=0;role<count;role++){if(!used.Add(ids[role]))valid=false;for(int i=0;i<props.m_MultiLights.Count;i++)if(props.m_MultiLights[i].layerId==ids[role])result[role]=i;if(result[role]<0)valid=false;else {var purpose=props.m_MultiLights[result[role]].purpose;var required=role%4==0?EmissiveProperties.Purpose.TrafficLight_Red:role%4==1?EmissiveProperties.Purpose.TrafficLight_Yellow:EmissiveProperties.Purpose.TrafficLight_Green;if(purpose!=required)valid=false;}}if(!valid)for(int i=0;i<8;i++)result[i]=-1;}_maps[mesh]=result;return result;}
 private int[] Ids(){var s=Mod.Settings;return new[]{s.RedId,s.YellowId,s.StraightId,s.ArrowId,s.RedId2,s.YellowId2,s.StraightId2,s.ArrowId2};}
 protected override void OnUpdate(){using(RuntimeDiagnostics.Measure("DirectionalLightSystem.OnUpdate")){var settings=Mod.Settings;if(!_ready||settings==null||!settings.Enabled||!settings.IndependentLights){Status="0 / 0";return;}if(_bindings.Count==0){Status="0 / 0";return;}var signature=settings.DirectionalTargets+":"+string.Join(",",Ids())+":"+settings.SecondHead+":"+Catalog.Version;if(signature!=_signature){_signature=signature;_maps.Clear();_leftThreeMaps.Clear();_normalThreeMaps.Clear();_targetNames.Clear();foreach(var name in DirectionalTargetNames.Parse(settings.DirectionalTargets))_targetNames.Add(name);}
 if(_lastKorean!=settings.KoreanTransitions||_lastAmber!=settings.AmberSeconds){foreach(var info in _info.Values){info.StraightTransition=default;info.LeftTransition=default;info.Frame=-1;}_lastKorean=settings.KoreanTransitions;_lastAmber=settings.AmberSeconds;}
 EntityManager.CompleteDependencyBeforeRO<Game.Net.LaneSignal>();EntityManager.CompleteDependencyBeforeRO<Game.Net.TrafficLights>();EntityManager.CompleteDependencyBeforeRW<Emissive>();EntityManager.CompleteDependencyBeforeRW<LightState>();var camera=World.GetExistingSystemManaged<CameraUpdateSystem>();if(camera==null)return;var position=camera.position;var cell=(int2)math.floor(position.xz/256f);int matched=0,checkedCount=0;var dead=new List<Entity>();for(int x=-3;x<=3;x++)for(int y=-3;y<=3;y++)if(_cells.TryGetValue(cell+new int2(x,y),out var set))foreach(var e in set){if(!Live(e)){dead.Add(e);continue;}if(!EntityManager.HasBuffer<Emissive>(e)||!EntityManager.HasBuffer<LightState>(e)||!EntityManager.HasComponent<PrefabRef>(e))continue;var b=_bindings[e];if(!Live(b.Source)||!EntityManager.HasComponent<Game.Net.TrafficLights>(b.Info.Owner))continue;if(math.distancesq(EntityManager.GetComponentData<Transform>(e).m_Position.xz,position.xz)>600*600)continue;checkedCount++;
 if(b.Info.Frame!=UnityEngine.Time.frameCount){var node=EntityManager.GetComponentData<Game.Net.TrafficLights>(b.Info.Owner);State(b.Info.Left,node,ref b.Info.LeftState,settings.IncludeYieldLeft);State(b.Info.Straight,node,ref b.Info.StraightState,false);if(settings.KoreanTransitions){uint frame=World.GetExistingSystemManaged<Game.Simulation.SimulationSystem>().frameIndex;uint duration=(uint)math.max(1,math.round(settings.AmberSeconds*60f));b.Info.StraightDisplay=b.Info.StraightTransition.Update((int)b.Info.StraightState.m_State,frame,duration);b.Info.LeftDisplay=b.Info.LeftTransition.Update((int)b.Info.LeftState.m_State,frame,duration);}else{b.Info.StraightDisplay=(int)b.Info.StraightState.m_State;b.Info.LeftDisplay=(int)b.Info.LeftState.m_State;}b.Info.Frame=UnityEngine.Time.frameCount;}
 var prefab=EntityManager.GetComponentData<PrefabRef>(e).m_Prefab;if(!EntityManager.HasBuffer<SubMesh>(prefab))continue;var meshes=EntityManager.GetBuffer<SubMesh>(prefab,true);var emissives=EntityManager.GetBuffer<Emissive>(e);var lights=EntityManager.GetBuffer<LightState>(e);for(int m=0;m<math.min(meshes.Length,emissives.Length);m++){var entry=emissives[m];if(entry.m_BufferAllocation.Empty||entry.m_LightOffset<0)continue;var mesh=meshes[m].m_SubMesh;var map=b.LeftThree||b.NormalThree?ThreeMap(mesh,b.LeftThree):Map(mesh,b.Four);if(map[0]<0||!EntityManager.HasBuffer<ProceduralLight>(mesh))continue;var definitions=EntityManager.GetBuffer<ProceduralLight>(mesh,true);bool valid=true;int count=b.LeftThree||b.NormalThree?3:settings.SecondHead?8:4;for(int i=0;i<count;i++)if(map[i]<0||map[i]>=definitions.Length||entry.m_LightOffset+map[i]>=lights.Length)valid=false;if(!valid)continue;matched++;for(int role=0;role<count;role++){int i=entry.m_LightOffset+map[role];var light=lights[i];bool on=b.LeftThree?LeftThreeLampRules.Lamp(role,b.Info.LeftDisplay):b.NormalThree?((b.Info.StraightDisplay&(1<<role))!=0):settings.KoreanTransitions?KoreanSignalTransition.Lamp(role%4,b.Info.StraightDisplay,b.Info.LeftDisplay):DirectionalLampRules.On(role%4,b.Info.StraightDisplay,b.Info.LeftDisplay);float value=on?1:0;if(light.m_Intensity!=value){light.m_Intensity=value;lights[i]=light;entry.m_Updated=true;}}for(int slot=0;slot<definitions.Length&&entry.m_LightOffset+slot<lights.Length;slot++){
 if(!DirectionalSlotRules.SuppressExtraGreen(slot,definitions[slot].m_Purpose==EmissiveProperties.Purpose.TrafficLight_Green,map,count))continue;
 int index=entry.m_LightOffset+slot;var extra=lights[index];if(extra.m_Intensity!=0){extra.m_Intensity=0;lights[index]=extra;entry.m_Updated=true;}
 }emissives[m]=entry;}}
 foreach(var e in dead)Unlink(e);Status=matched+" / "+checkedCount;
 }}
 internal static DropdownItem<string>[] MeshItems(string selected){var result=new List<DropdownItem<string>>();var w=World.DefaultGameObjectInjectionWorld;if(w!=null&&w.IsCreated){var em=w.EntityManager;var ps=w.GetExistingSystemManaged<PrefabSystem>();using(var query=em.CreateEntityQuery(ComponentType.ReadOnly<ProceduralLight>(),ComponentType.ReadOnly<PrefabData>()))using(var entities=query.ToEntityArray(Allocator.Temp))foreach(var e in entities)if(ps.TryGetPrefab<RenderPrefab>(e,out var p)&&p.TryGet<EmissiveProperties>(out var props)&&props.m_MultiLights!=null&&props.m_MultiLights.Count>=4)result.Add(new DropdownItem<string>{value=p.name,displayName=p.name});}result.Sort((a,b)=>string.CompareOrdinal(a.value,b.value));if(!result.Exists(i=>i.value==selected))result.Insert(0,new DropdownItem<string>{value=selected,displayName=selected+" [—]"});return result.ToArray();}
}
internal static class DirectionalLampRules{internal static bool On(int role,int straight,int left){switch(role){case 0:return (straight&1)!=0;case 1:return (straight&2)!=0;case 2:return (straight&4)!=0;case 3:return (left&4)!=0;default:return false;}}}
public partial class DirectionalIndexSystem:GameSystemBase{protected override void OnUpdate(){World.GetExistingSystemManaged<DirectionalLightSystem>()?.Index();}}
}
