using System;using System.Collections.Generic;using Game;using Game.Common;using Game.Objects;using Game.Prefabs;using Game.Tools;using Game.Rendering;using Unity.Entities;using Unity.Collections;using Unity.Mathematics;
namespace TrafficLightIntoKorea {
public struct FarSignal:IComponentData {}
public partial class FarSignalSystem:GameSystemBase {
 private readonly Dictionary<Entity,Entity> _requested=new Dictionary<Entity,Entity>();
 private readonly Dictionary<Entity,bool> _requestResults=new Dictionary<Entity,bool>();
 internal void TrackRequest(Entity owner,Entity source){_requestResults.Remove(source);_requested[source]=owner;Queue(owner);}
 internal void CancelRequest(Entity source){_requested.Remove(source);_requestResults.Remove(source);}
 internal bool TakeRequestResult(Entity source,out bool built){if(!_requestResults.TryGetValue(source,out built))return false;_requestResults.Remove(source);return true;}
 private void CompleteRequests(Entity owner,List<Plan> plans){var done=new List<Entity>();foreach(var r in _requested)if(r.Value==owner){_requestResults[r.Key]=plans.Exists(p=>p.Source==r.Key);done.Add(r.Key);}foreach(var source in done)_requested.Remove(source);}
 private readonly Dictionary<Entity,string> _placementReports=new Dictionary<Entity,string>();
 private readonly JunctionWatch _watch=new JunctionWatch();
 private readonly SignalStartupScan _startup=new SignalStartupScan();
 protected override void OnDestroy(){_startup.Dispose();base.OnDestroy();}
 private sealed class Entry{internal Entity Clone,Owner,Prefab,Pedestrian;internal KoreanSignalTransition Transition;internal int BatchAttempts;internal float NextBatch;internal bool OwnsPedestrianHidden,Manual;}
 private sealed class Plan{internal Entity Source,Prefab,Pedestrian;internal Transform Transform;internal bool Manual;}
 private readonly Dictionary<Entity,Entry> _entries=new Dictionary<Entity,Entry>();
 private readonly List<Entity> _pending=new List<Entity>(),_remove=new List<Entity>();private readonly HashSet<Entity> _queued=new HashSet<Entity>();private int _head;private bool _ready,_active,_saving;
 private float _lastInset=float.NaN;
 private EntityQuery _signals,_changed,_changedSignals;
 protected override void OnCreate(){base.OnCreate();_signals=GetEntityQuery(ComponentType.ReadOnly<TrafficLight>(),ComponentType.ReadOnly<Transform>(),ComponentType.ReadOnly<PrefabRef>(),ComponentType.Exclude<FarSignal>(),ComponentType.Exclude<ApproachVisual>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>());_changed=GetEntityQuery(ComponentType.ReadOnly<Game.Net.SubLane>(),ComponentType.ReadOnly<Game.Objects.SubObject>(),ComponentType.ReadOnly<Updated>(),ComponentType.Exclude<ApproachVisual>(),ComponentType.Exclude<Deleted>(),ComponentType.Exclude<Temp>());_changedSignals=GetEntityQuery(new EntityQueryDesc{All=new[]{ComponentType.ReadOnly<TrafficLight>(),ComponentType.ReadOnly<Owner>()},Any=new[]{ComponentType.ReadOnly<Created>(),ComponentType.ReadOnly<Updated>()},None=new[]{ComponentType.ReadOnly<FarSignal>(),ComponentType.ReadOnly<ApproachVisual>(),ComponentType.ReadOnly<Deleted>(),ComponentType.ReadOnly<Temp>()}});}
 protected override void OnGamePreload(Colossal.Serialization.Entities.Purpose purpose,GameMode mode){Clear();_ready=false;base.OnGamePreload(purpose,mode);}
 protected override void OnGameLoadingComplete(Colossal.Serialization.Entities.Purpose purpose,GameMode mode){base.OnGameLoadingComplete(purpose,mode);_ready=mode==GameMode.Game;_active=false;_startup.Reset();}
 private Entity OwnerOf(Entity e){if(!EntityManager.Exists(e))return Entity.Null;for(int i=0;i<4&&EntityManager.HasComponent<Owner>(e);i++){e=EntityManager.GetComponentData<Owner>(e).m_Owner;if(EntityManager.HasBuffer<Game.Net.SubLane>(e)&&EntityManager.HasBuffer<Game.Objects.SubObject>(e))return e;}return Entity.Null;}
 internal Entity DisplayFor(Entity source)=>_entries.TryGetValue(source,out var entry)&&Live(entry.Clone)?entry.Clone:Entity.Null;
 internal bool DisplayReady(Entity source)=>_entries.TryGetValue(source,out var entry)&&Live(entry.Clone)&&!EntityManager.HasComponent<Hidden>(entry.Clone)&&SignalRenderReadiness.MainReady(EntityManager,entry.Clone);
 internal void CollectOwners(HashSet<Entity> owners){foreach(var e in _entries.Values)owners.Add(e.Owner);}
 internal void RemoveOwner(Entity owner){CompleteRequests(owner,new List<Plan>());_placementReports.Remove(owner);_watch.Untrack(owner);_remove.Clear();foreach(var p in _entries)if(p.Value.Owner==owner)_remove.Add(p.Key);foreach(var e in _remove){ReleaseFar(_entries[e]);_entries.Remove(e);_missingSince.Remove(e);}_retryAt.Remove(owner);_retryUntil.Remove(owner);}
 internal void RefreshAll(){_startup.Request();}
 internal void RefreshOwner(Entity e){Queue(e);}
 private void Queue(Entity e){_watch.Track(e);if(e!=Entity.Null&&_queued.Add(e))_pending.Add(e);}
 private bool Live(Entity e)=>EntityManager.Exists(e)&&!EntityManager.HasComponent<Deleted>(e)&&!EntityManager.HasComponent<KoreanRetired>(e);
 internal void Clear(){_requested.Clear();_requestResults.Clear();_placementReports.Clear();ResetRetries();_watch.Clear();_startup.Reset();foreach(var pair in _entries)ReleaseFar(pair.Value);_entries.Clear();_pending.Clear();_queued.Clear();_head=0;_active=false;}
 private void Delete(Entity e){World.GetExistingSystemManaged<TrafficSignSystem>()?.Forget(e);if(Live(e))World.GetOrCreateSystemManaged<KoreanVisualLifecycleSystem>().Retire(e);}
 protected override void OnUpdate(){using(RuntimeDiagnostics.Measure("FarSignalSystem.OnUpdate")){if(_saving)return;bool on=_ready&&Mod.Settings!=null&&Mod.Settings.Enabled&&(Mod.Settings.AddFarSignals||(World.GetExistingSystemManaged<IndividualSignalData>()?.HasForcedFar??false));if(!on){if(_active)Clear();return;}
 if(!_active||_lastInset!=Mod.Settings.FarSidewalkInset){_active=true;_lastInset=Mod.Settings.FarSidewalkInset;_startup.Request();}
 TickRetries();
 _watch.Tick(EntityManager,Queue);
 
 
 for(int i=0;i<2&&_head<_pending.Count&&SignalWorkBudget.TakeOwner();i++){var owner=_pending[_head++];_queued.Remove(owner);Rebuild(owner);}if(_head==_pending.Count){_pending.Clear();_head=0;}
 }}
 internal void DescribePlacement(Entity owner,System.Text.StringBuilder report){report.AppendLine("FAR Ready="+_ready+" Active="+_active+" Saving="+_saving+" Pending="+(_pending.Count-_head));foreach(var p in _entries)if(p.Value.Owner==owner)report.AppendLine("EXISTING Source="+p.Key+" Clone="+p.Value.Clone+" Prefab="+p.Value.Prefab+" Live="+Live(p.Value.Clone));Rebuild(owner,report,true);}
 private void Rebuild(Entity owner,System.Text.StringBuilder report=null,bool inspect=false){using(RuntimeDiagnostics.Measure("Far.Rebuild"))RebuildCore(owner,report,inspect);} private void RebuildCore(Entity owner,System.Text.StringBuilder report,bool inspect){if(inspect&&report==null)report=new System.Text.StringBuilder();if(!KoreanJunctionSystem.Selected(EntityManager,owner)){if(!inspect)RemoveOwner(owner);return;}if(!Live(owner)||!EntityManager.HasBuffer<Game.Objects.SubObject>(owner)||!EntityManager.HasBuffer<Game.Net.SubLane>(owner)){report?.AppendLine("SKIP missing/live owner or SubObject/SubLane buffer");if(!inspect)CompleteRequests(owner,new List<Plan>());return;}bool needsRetry=false;var excluded=new HashSet<Entity>();var plans=new List<Plan>();var claimedPedestrians=new HashSet<Entity>();var roadSegments=RoadSegments(owner);var left=World.GetExistingSystemManaged<LeftSignalSystem>();var over=World.GetExistingSystemManaged<OverrideSystem>();
 using(var a=EntityManager.GetBuffer<Game.Objects.SubObject>(owner,true).ToNativeArray(Allocator.Temp))foreach(var item in a){var e=item.m_SubObject;if(!Live(e)||EntityManager.HasComponent<Temp>(e)||!EntityManager.HasComponent<TrafficLight>(e)||!EntityManager.HasComponent<Transform>(e)||!EntityManager.HasComponent<PrefabRef>(e))continue;var choice=World.GetExistingSystemManaged<IndividualSignalData>().Get(owner,e);bool force=choice?.farMode==1;if(choice?.farMode==0||(!Mod.Settings.AddFarSignals&&!force)){excluded.Add(e);continue;}if(choice?.manualPosition!=null){if(TryManualPlan(owner,e,choice,out var manualPlan))plans.Add(manualPlan);else excluded.Add(e);continue;}var prefab=EntityManager.GetComponentData<PrefabRef>(e).m_Prefab;report?.AppendLine("CHECK Source="+e+" Prefab="+prefab+" VehicleMask="+EntityManager.GetComponentData<TrafficLight>(e).m_GroupMask0);if((!over.IsOverridden(prefab)&&(World.GetExistingSystemManaged<ApproachSignalSystem>()?.VehicleTarget(e)??Entity.Null)==Entity.Null)||!EntityManager.HasComponent<ObjectData>(prefab)||!EntityManager.HasComponent<TrafficLightData>(prefab)||((int)EntityManager.GetComponentData<TrafficLightData>(prefab).m_Type&3)==0){report?.AppendLine("SKIP not replaced or not a supported vehicle source");continue;}
 // Only the retained right-side signal supplies a duplicate, even if hiding is disabled.
 if(!force&&left.HasRightReplacement(e)){report?.AppendLine("SKIP retained matching signal on right");continue;}var t=EntityManager.GetComponentData<Transform>(e);int mask=EntityManager.GetComponentData<TrafficLight>(e).m_GroupMask0;if(!SignalApproach.Try(EntityManager,owner,t,out int sourceRoad,out var direction)){needsRetry=true;report?.AppendLine("SKIP approach direction unresolved");continue;}report?.AppendLine("Origin="+t.m_Position+" Direction="+direction);
 if(TryApproachWidth(owner,t.m_Position,direction,mask,out float approachWidth)){report?.AppendLine("ApproachWidth="+approachWidth+" NarrowThreshold="+FarRoadRules.NarrowWidth);if(!force&&FarRoadRules.Narrow(approachWidth)){excluded.Add(e);report?.AppendLine("SKIP narrow approach road");continue;}}
 else report?.AppendLine("ApproachWidth=unknown (no width-based exclusion)");
 int destinationIndex=-1;float travel=0,rise=0;foreach(var sub in EntityManager.GetBuffer<Game.Net.SubLane>(owner,true)){var lane=sub.m_SubLane;if(!EntityManager.HasComponent<Game.Net.CarLane>(lane)||!EntityManager.HasComponent<Game.Net.LaneSignal>(lane)||!EntityManager.HasComponent<Game.Net.Curve>(lane))continue;var flags=EntityManager.GetComponentData<Game.Net.CarLane>(lane).m_Flags;if(!Live(lane)||EntityManager.HasComponent<Temp>(lane)||(flags&Game.Net.CarLaneFlags.Forbidden)!=0||!EntityManager.HasComponent<Game.Net.Lane>(lane)||EntityManager.GetComponentData<Game.Net.Lane>(lane).m_StartNode.GetOwnerIndex()!=sourceRoad)continue;var b=EntityManager.GetComponentData<Game.Net.Curve>(lane).m_Bezier;var start=math.normalizesafe((b.b-b.a).xz);var end=math.normalizesafe((b.d-b.c).xz);float distance=math.dot(b.d.xz-t.m_Position.xz,direction);if(MovementGeometry.Classify(flags,math.dot(start,end),start.x*end.y-start.y*end.x)!=1||!FarPlacementRules.Accept(distance,math.dot(start,direction),math.dot(end,direction),b.d.y-b.a.y))continue;if(distance>travel){travel=distance;rise=b.d.y-b.a.y;destinationIndex=EntityManager.GetComponentData<Game.Net.Lane>(lane).m_EndNode.GetOwnerIndex();}}
 report?.AppendLine("StraightTravel="+travel+" Rise="+rise);
 float inset=math.clamp(Mod.Settings.FarSidewalkInset,0f,3f);
 if(travel==0){if(TryTeeSidewalk(owner,t.m_Position,direction,inset,out var destination))t.m_Position=destination;else {needsRetry=true;report?.AppendLine("SKIP far sidewalk unresolved; no arbitrary 20m fallback");continue;}}
 else {bool lht=World.GetOrCreateSystemManaged<Game.City.CityConfigurationSystem>().leftHandTraffic;var outward=new float2(direction.y,-direction.x)*(lht?-1f:1f);t.m_Position+=new float3(direction.x*(travel+1f)+outward.x*inset,rise,direction.y*(travel+1f)+outward.y*inset);}
 var origin=EntityManager.GetComponentData<Transform>(e).m_Position;
 var destinationRoad=DestinationRoad(owner,destinationIndex);float corridor=FarDestinationRules.Corridor(approachWidth,RoadWidth(destinationRoad));if(!TrySafeSidewalk(owner,origin,direction,t.m_Position,travel,inset,roadSegments,out var safe,destinationRoad,corridor,report)){needsRetry=true;report?.AppendLine("SKIP no safe sidewalk in source forward corridor");continue;}t.m_Position=safe;report?.AppendLine("VEHICLE_DESTINATION="+safe);
var combined=CombinedPrefab(e,prefab);Entity pedestrian=Entity.Null;
 if(combined!=Entity.Null&&TryPedestrianAnchor(owner,e,origin,direction,t.m_Position,roadSegments,claimedPedestrians,out pedestrian,out var anchor,destinationRoad,report)){t.m_Position=anchor;report?.AppendLine("PEDESTRIAN_ANCHOR="+pedestrian+" Combined="+combined);}
 else {report?.AppendLine("VEHICLE_ONLY no compatible pedestrian within 4m on the same crossing end");}
 t=SignalAlignment.Align(EntityManager,owner,e,t);report?.AppendLine("ALIGNED rotation="+t.m_Rotation.value);float adjustment=FarOffsetRules.Clamp(choice?.farOffset??0);var offsetAxis=-math.rotate(t.m_Rotation,new float3(0,0,1));t.m_Position+=offsetAxis*adjustment;report?.AppendLine("MANUAL offset="+adjustment);float lateral=FarOffsetRules.Clamp(choice?.farLateral??0);var lateralAxis=new float3(offsetAxis.z,0,-offsetAxis.x);t.m_Position+=lateralAxis*lateral;report?.AppendLine("MANUAL lateral="+lateral);float rotation=FarOffsetRules.FarRotation(choice?.farRotation??0);t.m_Rotation=math.mul(quaternion.RotateY(math.radians(rotation)),t.m_Rotation);report?.AppendLine("MANUAL rotation="+rotation);
 bool occupied=false;foreach(var other in a){var o=other.m_SubObject;if(o==e||!Live(o)||!EntityManager.HasComponent<TrafficLight>(o)||!EntityManager.HasComponent<Transform>(o))continue;var ot=EntityManager.GetComponentData<Transform>(o);if(EntityManager.GetComponentData<TrafficLight>(o).m_GroupMask0!=0&&math.dot(math.rotate(ot.m_Rotation,new float3(0,0,1)),math.rotate(t.m_Rotation,new float3(0,0,1)))>.8f&&math.distancesq(ot.m_Position,t.m_Position)<1f){occupied=true;report?.AppendLine("SKIP occupied by same-facing vehicle signal="+o);break;}}report?.AppendLine("Destination="+t.m_Position);if(!occupied){var vehiclePrefab=pedestrian!=Entity.Null?combined:World.GetExistingSystemManaged<ApproachSignalSystem>()?.VehicleTarget(e)??Entity.Null;
 if(vehiclePrefab==Entity.Null&&!(World.GetExistingSystemManaged<ApproachSignalSystem>()?.ExpectsCustom(e)??false))vehiclePrefab=VehiclePrefab(prefab);report?.AppendLine(vehiclePrefab==Entity.Null?"SKIP display prefab unavailable":"PLAN prefab="+vehiclePrefab);if(vehiclePrefab==Entity.Null)needsRetry=true;if(vehiclePrefab!=Entity.Null){vehiclePrefab=World.GetExistingSystemManaged<IndividualSignalData>().Target(owner,e,vehiclePrefab,true);if(pedestrian!=Entity.Null&&((int)EntityManager.GetComponentData<TrafficLightData>(vehiclePrefab).m_Type&12)==0)pedestrian=Entity.Null;plans.Add(new Plan{Source=e,Prefab=vehiclePrefab,Transform=t,Pedestrian=pedestrian});if(pedestrian!=Entity.Null)claimedPedestrians.Add(pedestrian);}}}

 if(!inspect&&(needsRetry||(plans.Count==0&&excluded.Count==0)))RetryLater(owner);
 if(!inspect){var trace="plans="+plans.Count+" retry="+needsRetry;if(!_placementReports.TryGetValue(owner,out var previous)||previous!=trace){_placementReports[owner]=trace;RuntimeDiagnostics.Event("FAR placement owner="+owner+" "+trace);}}
 if(inspect){report?.AppendLine("PlanCount="+plans.Count+" (inspection only; no entities modified)");return;}
 CompleteRequests(owner,plans);
 _remove.Clear();bool unresolved=false;float now=UnityEngine.Time.realtimeSinceStartup;
 foreach(var pair in _entries)if(pair.Value.Owner==owner&&!plans.Exists(p=>p.Source==pair.Key)){
  bool sourceLive=Live(pair.Key)&&Live(pair.Value.Clone)&&EntityManager.HasComponent<TrafficLight>(pair.Key);
  bool excludedNow=excluded.Contains(pair.Key);
  if(!_missingSince.TryGetValue(pair.Key,out var since)){since=now;_missingSince[pair.Key]=since;}
  if(sourceLive&&!excludedNow){unresolved=true;RetryLater(owner);}
  if(!FarRoadRules.Keep(now-since,sourceLive,excludedNow))_remove.Add(pair.Key);
 }
 foreach(var source in _remove){ReleaseFar(_entries[source]);_entries.Remove(source);_missingSince.Remove(source);}
 if(!unresolved&&!needsRetry&&plans.Count>0){_retryAt.Remove(owner);_retryUntil.Remove(owner);}
 foreach(var plan in plans)_missingSince.Remove(plan.Source);
 foreach(var plan in plans){if(_entries.TryGetValue(plan.Source,out var old)&&Live(old.Clone)&&old.Prefab==plan.Prefab&&old.Pedestrian==plan.Pedestrian){if(old.Manual!=plan.Manual)old.Transition=default;old.Manual=plan.Manual;var t=EntityManager.GetComponentData<Transform>(old.Clone);if(math.distancesq(t.m_Position,plan.Transform.m_Position)>.001f||!t.m_Rotation.Equals(plan.Transform.m_Rotation)){RuntimeDiagnostics.Count("far.transformWrite");EntityManager.SetComponentData(old.Clone,plan.Transform);if(!EntityManager.HasComponent<Updated>(old.Clone))EntityManager.AddComponent<Updated>(old.Clone);}continue;}if(!DisplayCreationBudget.Take(UnityEngine.Time.frameCount)){Queue(owner);RuntimeDiagnostics.Count("display.creationDeferred");continue;}if(old!=null)ReleaseFar(old);
 // Fresh native instance: never copy MeshBatch/Emissive allocations from another object.
 var clone=EntityManager.CreateEntity(EntityManager.GetComponentData<ObjectData>(plan.Prefab).m_Archetype);EntityManager.AddComponent<FarSignal>(clone);EntityManager.AddComponent<KoreanSignalClone>(clone);EntityManager.AddComponentData(clone,new Owner{m_Owner=owner});EntityManager.AddComponentData(clone,new IndividualSignalLink{Source=plan.Source,Owner=owner,Far=true});EntityManager.SetComponentData(clone,new PrefabRef{m_Prefab=plan.Prefab});EntityManager.SetComponentData(clone,plan.Transform);if(EntityManager.HasComponent<PseudoRandomSeed>(clone)&&EntityManager.HasComponent<PseudoRandomSeed>(plan.Source))EntityManager.SetComponentData(clone,EntityManager.GetComponentData<PseudoRandomSeed>(plan.Source));EntityManager.SetComponentData(clone,DisplayState(plan.Source,plan.Pedestrian,plan.Manual));World.GetExistingSystemManaged<DirectionalLightSystem>()?.Link(clone,plan.Source);_entries[plan.Source]=new Entry{Clone=clone,Owner=owner,Prefab=plan.Prefab,Pedestrian=plan.Pedestrian,Manual=plan.Manual};if(plan.Pedestrian!=Entity.Null)_pedestrianEntries[plan.Pedestrian]=_entries[plan.Source];}
 }
 internal void Sync(){using(RuntimeDiagnostics.Measure("FarSignalSystem.Sync")){if(_saving)return;_remove.Clear();foreach(var pair in _entries){var e=pair.Value.Clone;if(!Live(pair.Key)||!Live(pair.Value.Owner)||!Live(e)||!EntityManager.HasComponent<TrafficLight>(pair.Key)){ReleaseFar(pair.Value);_missingSince.Remove(pair.Key);Queue(pair.Value.Owner);_remove.Add(pair.Key);continue;}if(pair.Value.Pedestrian!=Entity.Null&&(!Live(pair.Value.Pedestrian)||!EntityManager.HasComponent<TrafficLight>(pair.Value.Pedestrian))){var previous=pair.Value.Pedestrian;_pedestrianEntries.Remove(previous);if(pair.Value.OwnsPedestrianHidden&&Live(previous)&&PersistentSignalVisibility.HiddenOrOwned(EntityManager,previous)){PersistentSignalVisibility.Show(EntityManager,previous);if(!EntityManager.HasComponent<BatchesUpdated>(previous))EntityManager.AddComponent<BatchesUpdated>(previous);}pair.Value.Pedestrian=Entity.Null;pair.Value.OwnsPedestrianHidden=false;Queue(pair.Value.Owner);}SignalRenderReadiness.Repair(EntityManager,e,ref pair.Value.BatchAttempts,ref pair.Value.NextBatch);HidePedestrian(pair.Value);var state=DisplayState(pair.Key,pair.Value.Pedestrian,pair.Value.Manual);if(!pair.Value.Manual)state=SignalVisualTransition.Apply(ref pair.Value.Transition,state,World);if(!state.Equals(EntityManager.GetComponentData<TrafficLight>(e)))EntityManager.SetComponentData(e,state);World.GetExistingSystemManaged<TrafficSignSystem>()?.SyncParent(e);}foreach(var e in _remove)_entries.Remove(e);}}
 internal void BeforeSave(){_saving=true;foreach(var pair in _entries)if(Live(pair.Value.Clone)&&!EntityManager.HasComponent<Temp>(pair.Value.Clone))EntityManager.AddComponent<Temp>(pair.Value.Clone);}
 internal void AfterSave(){foreach(var pair in _entries)if(Live(pair.Value.Clone)&&EntityManager.HasComponent<Temp>(pair.Value.Clone)){EntityManager.RemoveComponent<Temp>(pair.Value.Clone);if(!EntityManager.HasComponent<BatchesUpdated>(pair.Value.Clone))EntityManager.AddComponent<BatchesUpdated>(pair.Value.Clone);}_saving=false;}
}
public partial class FarSignalSyncSystem:GameSystemBase {protected override void OnUpdate(){World.GetExistingSystemManaged<FarSignalSystem>()?.Sync();}}

}





