using System;using Colossal.UI.Binding;using Game;using Game.Common;using Game.SceneFlow;using Game.Tools;using Unity.Entities;
namespace TrafficLightIntoKorea {
public partial class IndividualSignalUI:Game.UI.UISystemBase {
 [Serializable] private sealed class AssetItem {public string name;public string thumbnail;}
 [Serializable] private sealed class PropItem {public string key,name,thumbnail;public bool enabled,pending;}
 [Serializable] private sealed class Menu {public AssetItem[] roadNames;public string roadName;public bool roadNameOriginal;public string title;public string currentAsset;public AssetItem[] assets;public string[] signs;public string[] selections;public bool[] mounts;public bool signTab;public bool propsTab;public PropItem[] props;public bool far;public bool nearHidden,farReady;public float farOffset,farRotation,farLateral;public string status;public string placeholder="Media/Placeholder.svg";}
 private Entity CurrentPrefab()=>EntityManager.HasComponent<Game.Prefabs.PrefabRef>(_entity)?EntityManager.GetComponentData<Game.Prefabs.PrefabRef>(_entity).m_Prefab:Entity.Null;
 private PropItem[] PropItems(){var over=World.GetExistingSystemManaged<OverrideSystem>();var data=World.GetExistingSystemManaged<IndividualSignalData>();var prefab=CurrentPrefab();var slots=over.Accessories(prefab);var result=new PropItem[slots.Length];var images=World.GetOrCreateSystemManaged<Game.UI.ImageSystem>();for(int i=0;i<slots.Length;i++){var slot=slots[i];var road=over.RoadNameFor(prefab);var shown=RoadNameRules.Valid(slot.Name)&&RoadNameRules.Valid(road)?over.RoadNamePrefab(road):slot.Prefab;string thumbnail=images.placeholderIcon;try{thumbnail=images.GetThumbnail(shown)??thumbnail;}catch(Exception){}bool on=over.AccessoryVisible(prefab,slot.Key);result[i]=new PropItem{key=slot.Key,name=RoadNameRules.Valid(slot.Name)&&RoadNameRules.Valid(road)?road:slot.Name,thumbnail=thumbnail,enabled=on,pending=on!=data.AccessoryEnabled(_link.Owner,_link.Source,_link.Far,slot.Key)};}return result;}
 private string RoadNameCurrent(){var over=World.GetExistingSystemManaged<OverrideSystem>();var selected=over.RoadNameFor(CurrentPrefab());if(!string.IsNullOrEmpty(selected))return selected;foreach(var slot in over.Accessories(CurrentPrefab()))if(RoadNameRules.Valid(slot.Name))return slot.Name;return "";}
 private AssetItem[] RoadNames(){var over=World.GetExistingSystemManaged<OverrideSystem>();if(!Array.Exists(over.Accessories(CurrentPrefab()),slot=>RoadNameRules.Valid(slot.Name)))return new AssetItem[0];var items=new System.Collections.Generic.List<AssetItem>();var images=World.GetOrCreateSystemManaged<Game.UI.ImageSystem>();foreach(var name in RoadNameRules.Names){var prefab=over.RoadNamePrefab(name);if(prefab==Entity.Null)continue;string thumb=images.placeholderIcon;try{thumb=images.GetThumbnail(prefab)??thumb;}catch(Exception){}items.Add(new AssetItem{name=name,thumbnail=thumb});}return items.ToArray();}
 private string CurrentAsset(){
  if(!EntityManager.HasComponent<Game.Prefabs.PrefabRef>(_entity))return "";
  var prefab=EntityManager.GetComponentData<Game.Prefabs.PrefabRef>(_entity).m_Prefab;
  var source=World.GetExistingSystemManaged<OverrideSystem>().VisualSource(prefab);
  if(source!=Entity.Null)prefab=source;
  foreach(var pair in Catalog.Entries)if(pair.Value==prefab)return pair.Key;
  return "";
 }
 private AssetItem[] AssetItems(){var names=World.GetExistingSystemManaged<IndividualSignalData>().Allowed();var items=new AssetItem[names.Length];var images=World.GetOrCreateSystemManaged<Game.UI.ImageSystem>();for(int i=0;i<names.Length;i++){string icon=images.placeholderIcon;try{if(Catalog.Entries.TryGetValue(names[i],out var e)&&EntityManager.Exists(e))icon=images.GetThumbnail(e)??images.placeholderIcon;}catch(Exception){icon=images.placeholderIcon;}items[i]=new AssetItem{name=names[i],thumbnail=icon};}return items;}
 internal bool Opened{get;private set;}private IndividualSignalLink _link;private Entity _entity;private string _command;private bool _installed;private float _replacementUntil;private string _shownAsset;private Entity _shownPrefab;
 public override GameMode gameMode=>GameMode.Game;
 protected override void OnCreate(){base.OnCreate();AddBinding(new TriggerBinding<string>("tlkIndividual","diagnostic",value=>RuntimeDiagnostics.Event("Individual UI "+(value??"").Substring(0,Math.Min(300,(value??"").Length)))));AddBinding(new TriggerBinding<string>("tlkIndividual","choose",Choose));}
 private bool Script(string script){try{var view=GameManager.instance?.userInterface?.view?.View;if(view==null)return false;view.ExecuteScript(script);return true;}catch(Exception e){_installed=false;RuntimeDiagnostics.Event("Individual UI unavailable: "+e.Message);return false;}}
 internal void Install(){if(_installed)return;try{_installed=Script(IndividualMenuScript.Read(typeof(IndividualSignalUI).Assembly));}catch(Exception e){_installed=false;RuntimeDiagnostics.Event("Individual menu load failed: "+e.Message);}}
 internal void Open(Entity e,IndividualSignalLink link){Install();if(!_installed)return;_entity=e;_link=link;Opened=true;_replacementUntil=0;Show("");}
 private static string PublicStatus(string status){if(!string.IsNullOrEmpty(IndividualSignalData.SaveProblem))return IndividualSignalData.SaveProblem;return !string.IsNullOrEmpty(status)&&(status.Contains("없")||status.Contains("못")||status.Contains("실패")||status.Contains("확인"))?status:"";}
 private void Show(string status,bool signTab=false,bool propsTab=false){var data=World.GetExistingSystemManaged<IndividualSignalData>();var signs=World.GetExistingSystemManaged<TrafficSignSystem>();var menu=new Menu{roadNames=RoadNames(),roadName=RoadNameCurrent(),roadNameOriginal=string.IsNullOrEmpty(World.GetExistingSystemManaged<OverrideSystem>().RoadNameFor(CurrentPrefab())),props=PropItems(),propsTab=propsTab,currentAsset=CurrentAsset(),signTab=signTab,signs=signs.AvailableSigns(),mounts=signs.MountKinds(_entity),selections=new[]{data.SignSelection(_link.Owner,_link.Source,_link.Far,1),data.SignSelection(_link.Owner,_link.Source,_link.Far,2),data.SignSelection(_link.Owner,_link.Source,_link.Far,3)},title=_link.Far?"맞은편 신호등 편집":"신호등 개별 편집",assets=AssetItems(),far=_link.Far,nearHidden=data.Get(_link.Owner,_link.Source)?.nearHidden??false,farReady=World.GetExistingSystemManaged<FarSignalSystem>()?.DisplayReady(_link.Source)??false,farLateral=FarOffsetRules.Clamp(data.Get(_link.Owner,_link.Source)?.farLateral??0),farRotation=FarOffsetRules.Rotation(data.Get(_link.Owner,_link.Source)?.farRotation??0),farOffset=FarOffsetRules.Clamp(data.Get(_link.Owner,_link.Source)?.farOffset??0),status=PublicStatus(status)};_shownAsset=menu.currentAsset;_shownPrefab=CurrentPrefab();if(!Script("window.tlkIndividual && window.tlkIndividual.show("+Newtonsoft.Json.JsonConvert.SerializeObject(menu, new Newtonsoft.Json.JsonSerializerSettings{StringEscapeHandling=Newtonsoft.Json.StringEscapeHandling.EscapeHtml})+");"))Opened=false;}
 internal void Close(){_command=null;Opened=false;if(_installed)Script("window.tlkIndividual && window.tlkIndividual.close();");}
 private void Choose(string value){if(!Opened)return;if(value=="close"){Close();return;}_command=value;}
 protected override void OnGamePreload(Colossal.Serialization.Entities.Purpose p,GameMode m){Close();_installed=false;base.OnGamePreload(p,m);}
 protected override void OnDestroy(){if(_installed)Script("window.tlkIndividual && window.tlkIndividual.dispose();");base.OnDestroy();}
 private bool Live(Entity e)=>EntityManager.Exists(e)&&!EntityManager.HasComponent<Deleted>(e)&&!EntityManager.HasComponent<KoreanRetired>(e);
 private bool Rebind(){using(var query=EntityManager.CreateEntityQuery(Unity.Entities.ComponentType.ReadOnly<IndividualSignalLink>(),Unity.Entities.ComponentType.Exclude<Deleted>(),Unity.Entities.ComponentType.Exclude<KoreanRetired>()))using(var entities=query.ToEntityArray(Unity.Collections.Allocator.Temp)){foreach(var e in entities){var link=EntityManager.GetComponentData<IndividualSignalLink>(e);if(link.Owner==_link.Owner&&link.Source==_link.Source&&link.Far==_link.Far){_entity=e;return true;}}}return false;}
 protected override void OnUpdate(){base.OnUpdate();if(!Opened)return;if(!Live(_link.Source)||!KoreanJunctionSystem.Selected(EntityManager,_link.Owner)){Close();return;}if(!Live(_entity)){if(!Rebind()){if(UnityEngine.Time.realtimeSinceStartup<_replacementUntil)return;Close();return;}}if(CurrentPrefab()!=_shownPrefab||CurrentAsset()!=_shownAsset)Show("");if(_command==null)return;var command=_command;_command=null;if(command.StartsWith("roadname:",StringComparison.Ordinal)){bool ok=World.GetExistingSystemManaged<IndividualSignalData>().SetRoadName(_entity,_link,command.Substring(9));if(ok)_replacementUntil=UnityEngine.Time.realtimeSinceStartup+5f;Show(ok?"":"도로명 표지판 에셋을 확인할 수 없습니다.",false,true);return;}if(command.StartsWith("lateral:",StringComparison.Ordinal)){bool ok=_link.Far&&World.GetExistingSystemManaged<IndividualSignalData>().Set(_link.Owner,_link.Source,"lateral",command.Substring(8),true);Show(ok?"좌우 위치를 적용했습니다.":"위치를 변경할 수 없습니다.");return;}if(command.StartsWith("rotation:",StringComparison.Ordinal)){bool ok=_link.Far&&World.GetExistingSystemManaged<IndividualSignalData>().Set(_link.Owner,_link.Source,"rotation",command.Substring(9),true);Show(ok?"회전을 적용했습니다.":"회전을 변경할 수 없습니다.");return;}if(command.StartsWith("offset:",StringComparison.Ordinal)){bool ok=_link.Far&&World.GetExistingSystemManaged<IndividualSignalData>().Set(_link.Owner,_link.Source,"offset",command.Substring(7),true);Show(ok?"위치를 적용했습니다.":"위치를 변경할 수 없습니다.");return;}if(command.StartsWith("prop:",StringComparison.Ordinal)){var parts=command.Split(':');bool ok=parts.Length==3&&(parts[2]=="0"||parts[2]=="1")&&World.GetExistingSystemManaged<IndividualSignalData>().SetAccessory(_entity,_link,parts[1],parts[2]=="1");if(ok)_replacementUntil=UnityEngine.Time.realtimeSinceStartup+5f;Show(ok?"요소 표시를 적용하고 있습니다.":"이 에셋에 미리 설정된 요소만 변경할 수 있습니다.",false,true);return;}if(command.StartsWith("sign:",StringComparison.Ordinal)){var parts=command.Split(':');if(parts.Length==3&&int.TryParse(parts[1],out var kind)&&World.GetExistingSystemManaged<TrafficSignSystem>().MountKinds(_entity)[Math.Max(0,Math.Min(2,kind-1))]&&World.GetExistingSystemManaged<IndividualSignalData>().SetSign(_link.Owner,_link.Source,_link.Far,kind,parts[2])){Show("",true);}else Show("표지판 위치 또는 에셋을 확인할 수 없습니다.",true);return;}string action=command.StartsWith("asset:",StringComparison.Ordinal)?"asset":command;string name=action=="asset"?command.Substring(6):"";
  if(World.GetExistingSystemManaged<IndividualSignalData>().Set(_link.Owner,_link.Source,action,name,_link.Far)){if(action=="delete"||action=="hideNear"){Close();}else{_replacementUntil=UnityEngine.Time.realtimeSinceStartup+5f;if(action=="restoreNear")Show("");}}else Show("대상을 확실히 확인할 수 없거나 이 에셋을 사용할 수 없습니다.");
 }
}
}
