using Game;using Game.Tools;using Game.Common;using Game.Prefabs;using Unity.Entities;using Unity.Jobs;using Unity.Mathematics;
namespace TrafficLightIntoKorea {
public class KoreanJunctionToolPrefab:PrefabBase {}
public partial class KoreanJunctionTool:ToolBaseSystem {
 internal Entity Hovered=>_hover;
 private PrefabBase _prefab;private Entity _hover;private bool _highlight;
 public override string toolID=>"TrafficLightIntoKorea.Junction";
 public override PrefabBase GetPrefab()=>_prefab;
 public override bool TrySetPrefab(PrefabBase p){if(!(p is KoreanJunctionToolPrefab))return false;_prefab=p;return true;}
 public override void InitializeRaycast(){base.InitializeRaycast();m_ToolRaycastSystem.typeMask=TypeMask.Net;m_ToolRaycastSystem.netLayerMask=Game.Net.Layer.Road;m_ToolRaycastSystem.collisionMask=CollisionMask.OnGround|CollisionMask.Overground;m_ToolRaycastSystem.raycastFlags|=RaycastFlags.SubElements;}
 private Game.Input.IProxyAction NativeAction(string name){var property=typeof(Game.Input.InputManager).GetProperty("toolActionCollection",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);var collection=property?.GetValue(Game.Input.InputManager.instance) as Game.Input.UIInputActionCollection;if(collection==null){RuntimeDiagnostics.Event("Downgrade input collection unavailable");return null;}foreach(var alias in collection.m_InputActions)if(alias.aliasName==name){string label=name=="Upgrade Net Edge"?"TLK Apply Korean":"TLK Restore Default";return alias.GetState(GetType().Name,(source,action,mask,transform)=>new Game.Input.DisplayNameOverride(source,action,label,alias.displayPriority,alias.m_DisplayMask,transform));}return null;}
 protected override void OnStartRunning(){base.OnStartRunning();applyActionOverride=NativeAction("Upgrade Net Edge");secondaryApplyActionOverride=NativeAction("Downgrade Net Edge");applyAction.shouldBeEnabled=true;secondaryApplyAction.shouldBeEnabled=true;cancelAction.shouldBeEnabled=false;}
 protected override void OnStopRunning(){Hover(Entity.Null);base.OnStopRunning();}
 private bool Junction(Entity e)=>EntityManager.Exists(e)&&!EntityManager.HasComponent<Deleted>(e)&&!EntityManager.HasComponent<Temp>(e)&&EntityManager.HasComponent<Game.Net.Node>(e)&&EntityManager.HasBuffer<Game.Net.ConnectedEdge>(e)&&EntityManager.GetBuffer<Game.Net.ConnectedEdge>(e,true).Length>=3;
 private float Diameter(Entity node){if(EntityManager.HasComponent<Game.Net.NodeGeometry>(node)){var b=EntityManager.GetComponentData<Game.Net.NodeGeometry>(node).m_Bounds;float d=math.cmax((b.max-b.min).xz);if(math.isfinite(d)&&d>0)return math.max(8f,d);}return 24f;}
 private void DrawHover(Entity node){var overlay=World.GetOrCreateSystemManaged<Game.Rendering.OverlayRenderSystem>();var buffer=overlay.GetBuffer(out var deps);deps.Complete();var pos=EntityManager.GetComponentData<Game.Net.Node>(node).m_Position;buffer.DrawCircle(new UnityEngine.Color(0.15f,0.65f,1f,0.35f),pos,Diameter(node));overlay.AddBufferWriter(default);}
 private void DirtyHighlight(Entity e){if(EntityManager.Exists(e)&&!EntityManager.HasComponent<BatchesUpdated>(e))EntityManager.AddComponent<BatchesUpdated>(e);}
 private Entity Find(Entity e,float3 hit){if(Junction(e))return e;if(!EntityManager.HasComponent<Game.Net.Edge>(e))return Entity.Null;var edge=EntityManager.GetComponentData<Game.Net.Edge>(e);Entity result=Entity.Null;float nearest=float.MaxValue;foreach(var n in new[]{edge.m_Start,edge.m_End})if(Junction(n)){float d=math.distancesq(hit,EntityManager.GetComponentData<Game.Net.Node>(n).m_Position);if(d<nearest&&d<=math.pow(math.max(30f,Diameter(n)*0.5f),2)){nearest=d;result=n;}}return result;}
 private void Hover(Entity e){if(_hover==e)return;if(_highlight&&EntityManager.Exists(_hover)&&EntityManager.HasComponent<Highlighted>(_hover)){EntityManager.RemoveComponent<Highlighted>(_hover);DirtyHighlight(_hover);}_hover=e;_highlight=false;if(e!=Entity.Null&&!EntityManager.HasComponent<Highlighted>(e)){EntityManager.AddComponent<Highlighted>(e);DirtyHighlight(e);_highlight=true;}}
 protected override JobHandle OnUpdate(JobHandle inputDeps){inputDeps.Complete();Entity node=Entity.Null;if(GetRaycastResult(out Entity owner,out RaycastHit hit)){node=Find(hit.m_HitEntity,hit.m_HitPosition);if(node==Entity.Null)node=Find(owner,hit.m_HitPosition);}Hover(node);if(node!=Entity.Null){DrawHover(node);if(applyAction.WasPressedThisFrame())World.GetExistingSystemManaged<KoreanJunctionSystem>().RequestSelect(node,true);else if(secondaryApplyAction.WasPressedThisFrame())World.GetExistingSystemManaged<KoreanJunctionSystem>().RequestSelect(node,false);}return inputDeps;}
}
}
