using Game;using Game.Modding;using Game.Prefabs;using Game.Serialization;using Game.SceneFlow;using Colossal.IO.AssetDatabase;using Unity.Entities;
namespace TrafficLightIntoKorea {
public sealed class Mod:IMod {
 internal static Settings Settings;
 public void OnLoad(UpdateSystem updates){updates.UpdateBefore<PersistentSignalVisibilitySystem,Game.Objects.SubObjectHiddenSystem>(SystemUpdatePhase.Modification5);updates.UpdateAt<MissingSignalAssetsSystem>(SystemUpdatePhase.UIUpdate);updates.UpdateBefore<FarVisibilitySystem>(SystemUpdatePhase.ModificationEnd);updates.UpdateBefore<FarVisibilitySystem,Game.Rendering.PreCullingSystem>(SystemUpdatePhase.PreCulling);updates.UpdateAt<IndividualSignalData>(SystemUpdatePhase.MainLoop);updates.UpdateAt<IndividualSignalUI>(SystemUpdatePhase.UIUpdate);updates.UpdateAt<IndividualSignalTool>(SystemUpdatePhase.ToolUpdate);Settings=new Settings(this);AssetDatabase.global.LoadSettings("TrafficLightIntoKorea",Settings,new Settings(this));Settings.Migrate(this);foreach(var lang in Locale.Languages)GameManager.instance.localizationManager.AddSource(lang,new Locale(Settings,lang));updates.UpdateAt<SignalDebugTool>(SystemUpdatePhase.ToolUpdate);updates.UpdateBefore<ApproachSignalSystem,FarSignalSystem>(SystemUpdatePhase.Modification5);updates.UpdateBefore<FarSignalSystem,TrafficSignSystem>(SystemUpdatePhase.Modification5);updates.UpdateBefore<FarSignalSyncSystem,Game.Rendering.ObjectInterpolateSystem>(SystemUpdatePhase.Rendering);updates.UpdateAt<DirectionalIndexSystem>(SystemUpdatePhase.ModificationEnd);updates.UpdateBefore<DirectionalLightSystem,Game.Rendering.ProceduralUploadSystem.Prepare>(SystemUpdatePhase.Rendering);updates.UpdateBefore<TrafficSignSystem,Game.Objects.SearchSystem>(SystemUpdatePhase.Modification5);updates.UpdateBefore<SignVisibilitySystem,Game.Rendering.PreCullingSystem>(SystemUpdatePhase.PreCulling);updates.UpdateBefore<ManualSignalPreviewSystem,KoreanVisualLifecycleSystem>(SystemUpdatePhase.Modification5);updates.UpdateBefore<KoreanVisualLifecycleSystem,ApproachSignalSystem>(SystemUpdatePhase.Modification5);updates.UpdateBefore<KoreanJunctionSystem,Game.Common.ModificationSystem>(SystemUpdatePhase.MainLoop);updates.UpdateAt<KoreanJunctionTool>(SystemUpdatePhase.ToolUpdate);updates.UpdateAt<KoreanJunctionTooltipSystem>(SystemUpdatePhase.UITooltip);updates.UpdateBefore<KoreanJunctionMenuSystem,PrefabInitializeSystem>(SystemUpdatePhase.PrefabUpdate);Settings.RegisterInOptionsUI();Settings.ApplyAndSave();updates.UpdateBefore<ApproachProxyPrepareSystem,PrefabInitializeSystem>(SystemUpdatePhase.PrefabUpdate);updates.UpdateAfter<OverrideSystem,ObjectInitializeSystem>(SystemUpdatePhase.PrefabUpdate);updates.UpdateBefore<PreDeserialize<OverrideSystem>>(SystemUpdatePhase.Deserialize);updates.UpdateBefore<OriginalSaveSystem,SerializerSystem>(SystemUpdatePhase.Serialize);updates.UpdateAfter<RestoreVisualSystem,SerializerSystem>(SystemUpdatePhase.Serialize);updates.UpdateBefore<LeftSignalSystem,ApproachVisibilitySystem>(SystemUpdatePhase.PreCulling);updates.UpdateBefore<ApproachVisibilitySystem,Game.Rendering.PreCullingSystem>(SystemUpdatePhase.PreCulling);}
 public void OnDispose(){SignalDebugTool.Stop();var w=World.DefaultGameObjectInjectionWorld;if(w!=null&&w.IsCreated){var tools=w.GetExistingSystemManaged<Game.Tools.ToolSystem>();if(tools!=null&&(tools.activeTool is KoreanJunctionTool||tools.activeTool is IndividualSignalTool))tools.activeTool=w.GetOrCreateSystemManaged<Game.Tools.DefaultToolSystem>();w.GetExistingSystemManaged<ManualSignalPreviewSystem>()?.BeforeSave();w.GetExistingSystemManaged<TrafficSignSystem>()?.Clear();w.GetExistingSystemManaged<DirectionalLightSystem>()?.Clear();w.GetExistingSystemManaged<FarSignalSystem>()?.Clear();w.GetExistingSystemManaged<ApproachSignalSystem>()?.Clear();w.GetExistingSystemManaged<LeftSignalSystem>()?.Reset();w.GetExistingSystemManaged<OverrideSystem>()?.Stop();w.GetExistingSystemManaged<PersistentSignalVisibilitySystem>()?.Stop();}Settings?.UnregisterInOptionsUI();Settings=null;}
}
}

