using System.Collections.Generic;using Game.Common;using Game.Prefabs;using Game.Tools;using Unity.Entities;using Unity.Mathematics;using Colossal.Mathematics;
namespace TrafficLightIntoKorea {
public partial class FarSignalSystem {
 private struct RoadSegment{internal float3 A,B;internal float Radius;}
 private List<Entity> LocalLanes(Entity owner){var result=new List<Entity>();var seen=new HashSet<Entity>();AddLanes(owner,result,seen);if(EntityManager.HasBuffer<Game.Net.ConnectedEdge>(owner))foreach(var e in EntityManager.GetBuffer<Game.Net.ConnectedEdge>(owner,true))if(Live(e.m_Edge)&&!EntityManager.HasComponent<Temp>(e.m_Edge))AddLanes(e.m_Edge,result,seen);return result;}
 private void AddLanes(Entity owner,List<Entity> result,HashSet<Entity> seen){if(EntityManager.HasBuffer<Game.Net.SubLane>(owner))foreach(var item in EntityManager.GetBuffer<Game.Net.SubLane>(owner,true)){var e=item.m_SubLane;if(Live(e)&&!EntityManager.HasComponent<Temp>(e)&&!EntityManager.HasComponent<Game.Net.MasterLane>(e)&&EntityManager.HasComponent<Game.Net.Curve>(e)&&seen.Add(e))result.Add(e);}}
 private float LaneWidth(Entity lane,float fallback){if(EntityManager.HasComponent<PrefabRef>(lane)){var prefab=EntityManager.GetComponentData<PrefabRef>(lane).m_Prefab;if(EntityManager.HasComponent<NetLaneData>(prefab)){float width=EntityManager.GetComponentData<NetLaneData>(prefab).m_Width;if(width>.1f)return width;}}return fallback;}
 private static float3 Point(Bezier4x3 b,float t){float u=1-t;return u*u*u*b.a+3*u*u*t*b.b+3*u*t*t*b.c+t*t*t*b.d;}
 private sealed class RoadSurface {
 internal readonly Dictionary<int2,List<RoadSegment>> Cells=new Dictionary<int2,List<RoadSegment>>();internal int Count;
 internal void Add(RoadSegment segment){Count++;var low=(int2)math.floor((math.min(segment.A.xz,segment.B.xz)-segment.Radius)/8f);var high=(int2)math.floor((math.max(segment.A.xz,segment.B.xz)+segment.Radius)/8f);for(int x=low.x;x<=high.x;x++)for(int y=low.y;y<=high.y;y++){var key=new int2(x,y);if(!Cells.TryGetValue(key,out var list)){list=new List<RoadSegment>();Cells[key]=list;}list.Add(segment);}}
 internal IEnumerable<RoadSegment> Near(float3 p,int range){var cell=(int2)math.floor(p.xz/8f);for(int x=-range;x<=range;x++)for(int y=-range;y<=range;y++)if(Cells.TryGetValue(cell+new int2(x,y),out var list))foreach(var item in list)yield return item;}
 }
 private RoadSurface RoadSegments(Entity owner){var result=new RoadSurface();foreach(var e in LocalLanes(owner)){if(!EntityManager.HasComponent<Game.Net.CarLane>(e)||(EntityManager.GetComponentData<Game.Net.CarLane>(e).m_Flags&Game.Net.CarLaneFlags.Forbidden)!=0)continue;var curve=EntityManager.GetComponentData<Game.Net.Curve>(e);var b=curve.m_Bezier;float radius=LaneWidth(e,3.5f)*.5f+.45f;var last=b.a;int count=math.clamp((int)math.ceil(curve.m_Length/2f),8,128);radius+=.75f*math.max(math.length(b.a-2*b.b+b.c),math.length(b.b-2*b.c+b.d))/(count*count);for(int i=1;i<=count;i++){var next=Point(b,(float)i/count);result.Add(new RoadSegment{A=last,B=next,Radius=radius});last=next;}}return result;}
 private static float2 Closest(float2 p,float2 a,float2 b){var d=b-a;return a+d*math.saturate(math.dot(p-a,d)/math.max(.0001f,math.lengthsq(d)));}
 private static bool ClearRoad(float3 p,RoadSurface segments,bool nativeAnchor=false){foreach(var segment in segments.Near(p,0)){if(math.abs((segment.A.y+segment.B.y)*.5f-p.y)>3f)continue;if(LaneClearance.DistanceSquared(p.x,p.z,segment.A.x,segment.A.z,segment.B.x,segment.B.z)<math.pow(math.max(.1f,segment.Radius-(nativeAnchor?.45f:0)),2))return false;}return true;}
 private bool OnDrivingSide(Entity owner,float3 origin,float2 direction,float3 point){
 if(!EntityManager.HasBuffer<Game.Net.ConnectedEdge>(owner))return false;float best=-2;float2 center=origin.xz;bool found=false;
 foreach(var item in EntityManager.GetBuffer<Game.Net.ConnectedEdge>(owner,true)){var e=item.m_Edge;if(!Live(e)||!EntityManager.HasComponent<Game.Net.Edge>(e)||!EntityManager.HasComponent<Game.Net.Curve>(e))continue;var edge=EntityManager.GetComponentData<Game.Net.Edge>(e);var b=EntityManager.GetComponentData<Game.Net.Curve>(e).m_Bezier;float2 toward;float2 end;if(edge.m_End==owner){toward=math.normalizesafe((b.d-b.c).xz);end=b.d.xz;}else if(edge.m_Start==owner){toward=math.normalizesafe((b.a-b.b).xz);end=b.a.xz;}else continue;float score=math.dot(toward,direction);if(score>best){best=score;center=end;found=true;}}
 if(!found||best<.7f)return false;bool lht=World.GetOrCreateSystemManaged<Game.City.CityConfigurationSystem>().leftHandTraffic;return DrivingSideRules.Accept(point.x-center.x,point.z-center.y,direction.x,direction.y,lht);
 }
 private bool TrySafeSidewalk(Entity owner,float3 origin,float2 direction,float3 desired,float travel,float inset,RoadSurface segments,out float3 result,Entity destination=default,float corridor=3f,System.Text.StringBuilder report=null){result=origin;if(segments.Count==0){report?.AppendLine("SIDEWALK no live driving lanes");return false;}float best=float.MaxValue;int lanes=0,samples=0,geometry=0,blocked=0,wrongSide=0,accepted=0;
 foreach(var e in LocalLanes(owner)){if(!EntityManager.HasComponent<Game.Net.PedestrianLane>(e)||(EntityManager.GetComponentData<Game.Net.PedestrianLane>(e).m_Flags&(Game.Net.PedestrianLaneFlags.Crosswalk|Game.Net.PedestrianLaneFlags.OnWater))!=0)continue;
 lanes++;var curve=EntityManager.GetComponentData<Game.Net.Curve>(e);float width=LaneWidth(e,0);if(width<.7f)continue;var b=curve.m_Bezier;int count=math.clamp((int)math.ceil(curve.m_Length),8,128);
 for(int i=0;i<=count;i++){samples++;var point=Point(b,(float)i/count);float progress=math.dot(point.xz-origin.xz,direction);if(progress<math.max(5f,travel*.65f)||progress>120f||math.abs(point.y-origin.y)>3f||math.distancesq(point.xz,desired.xz)>1600f)continue;
 var estimate=point.xz-desired.xz;if(math.abs(estimate.x*direction.y-estimate.y*direction.x)>corridor+width*.5f||math.abs(math.dot(estimate,direction))>math.max(5f,travel*.15f)+width*.5f){geometry++;continue;}float nearest=float.MaxValue;float2 away=0;foreach(var road in segments.Near(point,2)){if(math.abs((road.A.y+road.B.y)*.5f-point.y)>3)continue;var delta=point.xz-Closest(point.xz,road.A.xz,road.B.xz);float distance=math.lengthsq(delta);if(distance<nearest){nearest=distance;away=math.normalizesafe(delta);}}
 // Stay inside the actual pedestrian strip; inset is measured from its road-facing edge.
 for(int attempt=0;attempt<3;attempt++){float chosenInset=attempt==0?math.clamp(inset,.35f,width-.35f):attempt==1?width*.5f:width-.35f;float offset=-width*.5f+chosenInset;var candidate=point+new float3(away.x*offset,0,away.y*offset);
 var error=candidate.xz-desired.xz;float lateral=error.x*direction.y-error.y*direction.x;float longitudinal=math.dot(error,direction);if(!FarDestinationRules.Sidewalk(math.dot(candidate.xz-origin.xz,direction),lateral,longitudinal,candidate.y-origin.y,travel,corridor)){geometry++;continue;}if(nearest==float.MaxValue||!ClearRoad(candidate,segments)){blocked++;continue;}if(!(destination!=Entity.Null?OnDestinationSide(owner,destination,direction,candidate):OnDrivingSide(owner,origin,direction,candidate))){wrongSide++;continue;}accepted++;float score=math.distancesq(candidate.xz,desired.xz)+math.abs(chosenInset-inset);if(score<best){best=score;result=candidate;}}

 }}report?.AppendLine("SIDEWALK destination="+destination+" corridor="+corridor+" lanes="+lanes+" samples="+samples+" geometryRejected="+geometry+" roadBlocked="+blocked+" wrongRoadSide="+wrongSide+" accepted="+accepted);return best<float.MaxValue;}
}
}

