<Project Sdk="Microsoft.NET.Sdk">
 <PropertyGroup><Version>2.3.40</Version><AssemblyTitle>TRAFFIC LIGHT INTO KOREA</AssemblyTitle><Product>TRAFFIC LIGHT INTO KOREA</Product><AssemblyName>TrafficLightIntoKorea</AssemblyName></PropertyGroup>
 <Import Project="$(CSII_TOOLPATH)\Mod.props" />
 <Import Project="$(CSII_TOOLPATH)\Mod.targets" />
 <PropertyGroup>
  <UserDataPath>$(CSII_USERDATAPATH)</UserDataPath>
  <LocalModsPath>$(CSII_LOCALMODSPATH)</LocalModsPath>
  <UnityModProjectPath>$(CSII_UNITYMODPROJECTPATH)</UnityModProjectPath>
  <ModPostProcessorPath>$(CSII_MODPOSTPROCESSORPATH)</ModPostProcessorPath>
  <ModPublisherPath>$(CSII_MODPUBLISHERPATH)</ModPublisherPath>
  <MSCORLIBPath>$(CSII_MSCORLIBPATH)</MSCORLIBPath>
 </PropertyGroup><ItemGroup>
<Reference Include="Newtonsoft.Json"><Private>false</Private></Reference><Reference Include="cohtml.Net"><Private>false</Private></Reference><Reference Include="UnityEngine.JSONSerializeModule"><Private>false</Private></Reference><Reference Include="Game"><Private>false</Private></Reference>
<Reference Include="Colossal.Collections"><Private>false</Private></Reference>
<Reference Include="Colossal.Core"><Private>false</Private></Reference>
<Reference Include="Colossal.Logging"><Private>false</Private></Reference>
<Reference Include="Colossal.IO.AssetDatabase"><Private>false</Private></Reference>
<Reference Include="Colossal.Localization"><Private>false</Private></Reference>
<Reference Include="Colossal.UI"><Private>false</Private></Reference>
<Reference Include="Colossal.UI.Binding"><Private>false</Private></Reference>
<Reference Include="Colossal.Mathematics"><Private>false</Private></Reference>
<Reference Include="UnityEngine.AudioModule"><Private>false</Private></Reference>
<Reference Include="UnityEngine.CoreModule"><Private>false</Private></Reference>
<Reference Include="Unity.Burst"><Private>false</Private></Reference>
<Reference Include="Unity.Collections"><Private>false</Private></Reference>
<Reference Include="Unity.Entities"><Private>false</Private></Reference>

<Reference Include="Unity.Mathematics"><Private>false</Private></Reference>
</ItemGroup>
 <Target Name="DeployWIP" />
 <ItemGroup><None Include="../package/KoreanJunction.svg" Link="KoreanJunction.svg" CopyToOutputDirectory="PreserveNewest" /></ItemGroup>
<ItemGroup><EmbeddedResource Include="../package/IndividualSignals.js" LogicalName="TrafficLightIntoKorea.IndividualSignals.js" /><None Include="../package/IndividualSignals.js" Link="IndividualSignals.js" CopyToOutputDirectory="PreserveNewest" /><None Include="../package/IndividualSignal.svg" Link="IndividualSignal.svg" CopyToOutputDirectory="PreserveNewest" /></ItemGroup><ItemGroup><None Include="../package/Icons/*.svg" Link="Icons/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" /></ItemGroup><ItemGroup><EmbeddedResource Include="../package/lang/*.json" LogicalName="TrafficLightIntoKorea.lang.%(Filename)%(Extension)" /><None Include="../package/lang/*.json" Link="lang/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" /></ItemGroup></Project>









