using System;using System.Linq;using Game.Common;using Game.Tools;using Game.Objects;using Unity.Entities;using TrafficLightIntoKorea;
class Program {
 static int count;static void Check(bool ok,string label){count++;if(!ok)throw new Exception(label);}
 static Entity Make(EntityManager em,Entity parent){var e=em.Create();em.AddComponent<Game.Objects.Object>(e);em.AddComponentData(e,new Owner{m_Owner=parent});return e;}
 static void Main(){var world=new World();var em=world.Manager;var native=world.GetOrCreateSystemManaged<SubObjectHiddenSystem>();var original=native.Query;var parent=em.Create();var lights=Enumerable.Range(0,64).Select(_=>Make(em,parent)).ToArray();
  foreach(var e in lights)PersistentSignalVisibility.Hide(em,e);int old=0;for(int i=0;i<600;i++){native.Tick();foreach(var e in lights)if(!em.HasComponent<Hidden>(e)){old++;PersistentSignalVisibility.Hide(em,e);}}Check(old==38400,"baseline native unhide repeats each frame");
  var system=world.GetOrCreateSystemManaged<PersistentSignalVisibilitySystem>();Check(PersistentSignalVisibility.Enabled&&!native.Query.Equals(original),"native query adapter installed");foreach(var e in lights)PersistentSignalVisibility.Hide(em,e);int writes=em.Writes;for(int i=0;i<600;i++){native.Tick();foreach(var e in lights)PersistentSignalVisibility.Hide(em,e);}Check(em.Writes==writes&&lights.All(e=>em.HasComponent<Hidden>(e)),"stable hidden state has zero writes");
  var unrelated=Make(em,parent);em.AddComponent<Hidden>(unrelated);native.Tick();Check(!em.HasComponent<Hidden>(unrelated),"native cleanup still processes unrelated props");
  system.BeforeSave();Check(lights.All(e=>!em.HasComponent<KoreanPersistentHidden>(e)),"save strips all protection tags");system.AfterSave();Check(lights.All(e=>em.HasComponent<KoreanPersistentHidden>(e)),"post-save restores protections");system.AfterSave();Check(lights.All(e=>em.HasComponent<KoreanPersistentHidden>(e)),"post-save idempotent");
  PersistentSignalVisibility.Show(em,lights[0]);Check(!em.HasComponent<Hidden>(lights[0])&&!em.HasComponent<KoreanPersistentHidden>(lights[0]),"release clears hide and owned marker");
  em.RemoveComponent<Hidden>(lights[1]);Check(PersistentSignalVisibility.HiddenOrOwned(em,lights[1]),"externally cleared hide retains tracked ownership");PersistentSignalVisibility.Show(em,lights[1]);Check(!em.HasComponent<KoreanPersistentHidden>(lights[1]),"release cleans marker even after external hide removal");system.Stop();Check(native.Query.Equals(original)&&!PersistentSignalVisibility.Enabled,"unload restores original native query");Check(lights.All(e=>!em.HasComponent<Hidden>(e)&&!em.HasComponent<KoreanPersistentHidden>(e)),"unload restores all owned hidden objects");system.Stop();Check(native.Query.Equals(original),"unload idempotent");
  for(int i=0;i<4;i++)Check(DisplayCreationBudget.Take(100),"four shared near/far slots");Check(!DisplayCreationBudget.Take(100),"fifth signal deferred");Check(DisplayCreationBudget.Take(101),"next frame progresses");
  Console.WriteLine($"PASS: {count} visibility/creation checks. Baseline re-hides={old}; protected stable writes=0 for 64 signals x 600 frames. Native-query contract fixture, not in-game rendering.");
 }
}
